import {auth,db} from '../../firebase-config.js';
import {addDoc,collection,doc,documentId,getDoc,getDocs,limit,orderBy,query,runTransaction,startAfter,where} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import {can} from '../../ims-permissions.js';
import {applyInventorySummaryDelta,combineInventorySummaryDeltas,inventorySummaryDelta} from '../inventory/inventory-summary.js';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
const now=()=>new Date().toISOString();
const cls='w-full min-w-0 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm';
const VALID=new Set(['At Supplier','Available','Reserved','At Client','Maintenance','Inspection','Not Available','In Transit','Missing','Stolen']);
const ACTIONS={
 RECEIVE_SUPPLIER:{label:'Receive from Supplier',from:'supplier',to:'warehouse',toStatus:'Available',refType:'wellora_po',refLabel:'Wellora PO'},
 TRANSFER_WAREHOUSE:{label:'Transfer Warehouse / Location',from:'warehouse',to:'warehouse',toStatus:'Available',refType:'internal_transfer',refLabel:'Internal Transfer No.'},
 DELIVER_CLIENT:{label:'Rental / Send to Client',from:'warehouse',to:'client',toStatus:'At Client',refType:'client_po',refLabel:'Client PO'},
 RETURN_CLIENT:{label:'Return from Client',from:'client',to:'warehouse',toStatus:'Available',refType:'receiving_no',refLabel:'Receiving No.'}
};
let inventory=[],settings=[],businesses=[],groups=[],reservations=[],saving=false;
const roles=x=>Array.isArray(x.businessRoles)?x.businessRoles:[];
const isRole=(x,r)=>roles(x).includes(r);
const partyName=x=>x?.companyName||x?.supplierName||x?.clientName||'';
const action=()=>ACTIONS[$('bmAction')?.value||'DELIVER_CLIENT'];
function rememberMovement(){try{sessionStorage.setItem('ims.workspace.tab','movement');}catch{}}
function balances(i){return(Array.isArray(i?.stockBalances)?i.stockBalances:[]).filter(x=>Number(x.qty||0)>0).map(x=>({...x,qty:Number(x.qty||0),locationName:x.locationName||'Unknown',status:VALID.has(x.status)?x.status:'Not Available'}));}
function summary(b){const p=b.filter(x=>x.qty>0),priority=['In Transit','Maintenance','Inspection','At Client','Reserved','Missing','Stolen','Not Available','At Supplier','Available'];return!p.length?{status:'Not Available',location:'No Stock'}:{status:priority.find(s=>p.some(x=>x.status===s))||'Not Available',location:p.length===1?p[0].locationName:`${p.length} Locations`};}
function warehouses(){return settings.filter(x=>x.type==='warehouse'&&x.status!=='inactive').map(x=>({id:x.id,name:x.value})).filter(x=>x.name).sort((a,b)=>a.name.localeCompare(b.name));}
function suppliers(){return businesses.filter(x=>isRole(x,'supplier')).sort((a,b)=>partyName(a).localeCompare(partyName(b)));}
function clients(){return businesses.filter(x=>isRole(x,'client')).sort((a,b)=>partyName(a).localeCompare(partyName(b)));}
function logisticsProviders(){return businesses.filter(x=>isRole(x,'logistics')).sort((a,b)=>partyName(a).localeCompare(partyName(b)));}
function itemType(item){return settings.find(x=>x.type==='item_type'&&x.id===item?.itemTypeId)||settings.find(x=>x.type==='item_type'&&norm(x.value)===norm(item?.type));}
function singleItem(item){return itemType(item)?.quantityMode==='single';}
async function load(){const[a,b,c]=await Promise.all(['settings','client_profiles','supplier_profiles'].map(n=>getDocs(collection(db,n))));settings=a.docs.map(x=>({id:x.id,...x.data()}));businesses=[...b.docs.map(x=>({id:x.id,...x.data()})),...c.docs.map(x=>({id:x.id,...x.data()}))].filter(x=>x.status!=='inactive');inventory=[];await Promise.all([loadGroupsForAction(),loadReservations()]);}
async function loadGroupsForAction(){const a=action(),snap=await getDocs(query(collection(db,'movement_groups'),where('referenceType','==',a.refType))),movementGroups=snap.docs.map(x=>({id:x.id,persisted:true,...x.data()})).filter(x=>x.status!=='closed');if(a.refType!=='wellora_po'){groups=movementGroups;return groups;}const regSnap=await getDocs(query(collection(db,'registration_batches'),where('completionStatus','==','completed'))),seen=new Set(movementGroups.map(g=>`${norm(g.referenceNumber)}|${String(g.partyId||'')}`)),registered=[];for(const d of regSnap.docs){const r={id:d.id,...d.data()},po=String(r.ourPONumber||'').trim(),supplierId=String(r.supplierId||'');if(!po)continue;const key=`${norm(po)}|${supplierId}`;if(seen.has(key))continue;seen.add(key);registered.push({id:`registration:${d.id}`,persisted:false,registrationBatchId:d.id,referenceType:'wellora_po',referenceLabel:'Wellora PO',referenceNumber:po,partyId:supplierId,partyName:r.supplierName||'',status:'open',batchCount:0,fromId:supplierId,fromName:r.supplierName||'',registeredItemCount:Number(r.completedCount||r.quantity||0),registeredAt:r.completedAt||r.createdAt||''});}groups=[...movementGroups,...registered];return groups;}
async function loadReservations(){const snap=await getDocs(query(collection(db,'reservation_events'),where('status','==','Open'),orderBy(documentId(),'asc')));reservations=snap.docs.map(x=>({id:x.id,...x.data()}));return reservations;}
function reservationRecords(){return reservations.map(r=>{const lines=(Array.isArray(r.lines)?r.lines:[]).map(l=>({item:{id:l.itemId,alias:l.itemAlias||'',itemCode:l.itemCode||'',name:l.itemName||''},reservation:r,qty:Number(l.qty||0)}));return{id:r.reservationId||r.id,reservation:r,lines,total:Number(r.qty||r.batchQty||lines.reduce((n,l)=>n+l.qty,0))};});}
function selectedReservation(){const id=$('bmReservation')?.value||'';return reservationRecords().find(x=>x.id===id)||null;}
function reservedIds(){return new Set((selectedReservation()?.lines||[]).map(x=>x.item.id));}
function source(){const e=$('bmSource'),o=e?.selectedOptions?.[0];return e?.value?{id:e.value,name:o?.dataset?.name||o?.textContent?.trim()||''}:null;}
function destination(){const e=$('bmDestination'),o=e?.selectedOptions?.[0];return e?.value?{id:e.value,name:o?.dataset?.name||o?.textContent?.trim()||''}:null;}
function sameLocation(b,l){return b&&l&&((b.locationId&&String(b.locationId)===String(l.id))||norm(b.locationName)===norm(l.name));}
function sourceList(){const a=action();if(a.from==='warehouse')return warehouses();if(a.from==='supplier')return suppliers().map(x=>({id:x.id,name:partyName(x)}));return clients().map(x=>({id:x.id,name:partyName(x)}));}
function destinationList(){const a=action(),s=source();if(a.to==='warehouse')return warehouses().filter(x=>!s||String(x.id)!==String(s.id));return clients().map(x=>({id:x.id,name:partyName(x)}));}
function options(list,label){return`<option value="">-- ${esc(label)} --</option>${list.map(x=>`<option value="${esc(x.id)}" data-name="${esc(x.name)}">${esc(x.name)}</option>`).join('')}`;}
function eligibleBalance(item){const a=action(),s=source();if(!s)return null;const list=balances(item).filter(b=>sameLocation(b,s));if(a.from==='supplier')return list.find(b=>b.locationType==='supplier'&&b.status==='At Supplier')||null;if(a.from==='client')return list.find(b=>b.locationType==='client'&&b.status==='At Client')||null;if(a.from==='warehouse'){const warehouse=list.filter(b=>b.locationType==='warehouse');if(a.to==='client'){const rr=selectedReservation();if(rr&&rr.lines.some(x=>x.item.id===item.id)){const reserved=warehouse.find(b=>b.status==='Reserved'&&String(b.reservationId||'')===String(rr.id));if(reserved)return reserved;return null;}}return warehouse.find(b=>b.status==='Available')||null;}return null;}
function selectedIds(){return new Set([...document.querySelectorAll('.bmLine')].map(x=>x.dataset.itemId).filter(Boolean));}
function cacheItem(item){inventory=inventory.filter(x=>x.id!==item.id);inventory.push(item);}
async function findItem(){const s=source();if(!s)return alert('Select Source first.');const field=$('bmLookupField')?.value||'alias',value=$('bmLookupValue')?.value.trim()||'';if(!value)return alert('Enter an exact Wellora SN / R2R SN or Description.');const snap=await getDocs(query(collection(db,'inventory'),where(field,'==',value),limit(2)));if(!snap.size)return alert('No exact inventory item found.');if(snap.size>1)return alert('More than one exact item matched. Use Wellora SN / R2R SN.');const d=snap.docs[0],item={id:d.id,...d.data()};if(selectedIds().has(item.id))return alert('This item is already added to this movement batch.');const b=eligibleBalance(item);if(!b)return alert(`${item.alias||item.itemCode} is not eligible at ${s.name} for this movement type.`);cacheItem(item);addItem(item);}
function looseCategoryOptions(){const values=[...new Set(settings.filter(x=>x.type==='category'&&x.status!=='inactive').map(x=>String(x.value||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));return`<option value="">All Categories</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}`;}
function looseMatches(item,term,category){if(category&&norm(item.category)!==norm(category))return false;const q=norm(term);if(!q)return true;return norm(item.alias).startsWith(q)||norm(item.itemCode).startsWith(q)||norm(item.r2rSerial||item.r2rSN||item.r2rSn||'').startsWith(q)||norm(item.name).includes(q);}
function renderLooseResults(items){const box=$('bmLooseResults');if(!box)return;if(!items.length){box.innerHTML='<div class="py-2 text-slate-500">No eligible items match.</div>';return;}box.innerHTML=`<div class="hidden lg:grid grid-cols-[160px_minmax(0,1fr)_150px_180px_80px_auto] gap-3 px-3 text-[10px] uppercase tracking-wide text-slate-600"><span>Wellora / R2R SN</span><span>Description</span><span>Category</span><span>Location</span><span>Unit</span><span></span></div><div class="space-y-2 mt-2">${items.map(i=>`<div class="grid lg:grid-cols-[160px_minmax(0,1fr)_150px_180px_80px_auto] gap-3 items-center border border-slate-800 rounded-lg px-3 py-2"><div class="font-semibold text-cyan-300">${esc(i.alias||'—')}</div><div class="text-xs text-slate-300">${esc(i.name||'')}</div><div class="text-[11px] text-slate-400">${esc(i.category||'—')}</div><div class="text-[11px] text-slate-400">${esc(i.currentLocation||'—')}</div><div class="text-[10px] text-slate-500">${esc(i.unit||'')}</div><button type="button" class="bmLooseAdd bg-slate-700 hover:bg-slate-600 px-3 py-2 rounded-lg text-xs" data-id="${esc(i.id)}">Add</button></div>`).join('')}</div><div class="text-[11px] text-slate-500 pt-2">Showing up to 20 eligible matches.</div>`;box.querySelectorAll('.bmLooseAdd').forEach(btn=>btn.onclick=()=>{const item=items.find(i=>i.id===btn.dataset.id);if(!item)return;if(selectedIds().has(item.id))return;cacheItem(item);addItem(item);btn.closest('div.grid')?.remove();});}
async function looseSearch(){const s=source(),box=$('bmLooseResults');if(!box)return;if(!s){box.textContent='Select Source first.';return;}const term=$('bmLooseValue')?.value.trim()||'',category=$('bmLooseCategory')?.value||'';box.textContent='Searching eligible items…';try{const out=[],selected=selectedIds();let cursor=null,done=false,guard=0;while(out.length<20&&!done&&guard<40){guard++;const q=cursor?query(collection(db,'inventory'),orderBy(documentId(),'asc'),startAfter(cursor),limit(50)):query(collection(db,'inventory'),orderBy(documentId(),'asc'),limit(50));const snap=await getDocs(q);if(!snap.size){done=true;break;}for(const d of snap.docs){const item={id:d.id,...d.data()};if(!selected.has(item.id)&&eligibleBalance(item)&&looseMatches(item,term,category)){out.push(item);if(out.length===20)break;}}cursor=snap.docs.at(-1);if(snap.size<50)done=true;}renderLooseResults(out);}catch(e){box.textContent='Loose search failed: '+(e?.message||e);}}
function lineHtml(item){const b=eligibleBalance(item),locked=singleItem(item),max=locked?1:b.qty;return`<div class="bmLine border border-slate-800 rounded-xl p-3" data-item-id="${item.id}"><div class="grid sm:grid-cols-[1.05fr_1.8fr_.65fr_.65fr_auto] gap-2 items-end"><div><div class="text-[11px] text-slate-500">Wellora SN / R2R SN</div><div class="font-semibold text-cyan-300">${esc(item.alias||'—')}</div><div class="font-mono text-[9px] text-slate-600 mt-0.5">IMS Item ID: ${esc(item.itemCode||'')}</div></div><div><div class="text-[11px] text-slate-500">Description</div><div class="text-sm">${esc(item.name||'')}</div><div class="text-[10px] text-slate-500 mt-1">${esc(item.category||'')}${item.ourPONumber?` · PO ${esc(item.ourPONumber)}`:''}${item.currentLocation?` · ${esc(item.currentLocation)}`:''}</div></div><div><div class="text-[11px] text-slate-500">Eligible Qty</div><div class="text-sm">${b.qty} ${esc(item.unit||'')}</div></div><label class="text-xs text-slate-400">Qty<input class="bmQty ${cls} mt-1" type="number" min="1" max="${max}" step="1" value="1" ${locked?'readonly':''}></label><button type="button" class="bmRemove bg-slate-800 px-3 py-2.5 rounded-lg text-xs">Remove</button></div>${locked?'<div class="text-[10px] text-slate-600 mt-1">Single-unit item type — quantity locked at 1.</div>':''}</div>`;}
function addItem(item,qty=null){const w=$('bmLines'),b=eligibleBalance(item);if(!w||!b)return null;w.insertAdjacentHTML('beforeend',lineHtml(item));const row=w.lastElementChild,rowQty=row.querySelector('.bmQty'),max=singleItem(item)?1:b.qty;if(rowQty&&qty!==null){const requested=Number(qty||0);rowQty.value=String(Math.max(1,Math.min(max,Number.isFinite(requested)?requested:1)));}row.querySelector('.bmRemove').onclick=()=>row.remove();if($('bmLookupValue'))$('bmLookupValue').value='';return row;}
function clearItems(){inventory=[];if($('bmLines'))$('bmLines').innerHTML='';if($('bmLookupValue'))$('bmLookupValue').value='';if($('bmLooseResults'))$('bmLooseResults').innerHTML='<div class="text-slate-500">Enter a SN prefix / partial description, or choose a category.</div>';}
function field(l,b,extra=''){return`<label class="block min-w-0 text-xs text-slate-400 ${extra}">${l}${b}</label>`;}
function groupType(g){return g.referenceType||'';}
function groupNumber(g){return g.referenceNumber||'';}
function groupMatches(g,a){return groupType(g)===a.refType;}
function groupCandidates(){return groups.filter(g=>groupMatches(g,action())).sort((x,y)=>String(y.updatedAt||y.registeredAt||y.createdAt||'').localeCompare(String(x.updatedAt||x.registeredAt||x.createdAt||'')));}
function groupLabel(g){const n=groupNumber(g)||'No Reference',party=g.partyName||((g.fromName&&g.toName)?`${g.fromName} → ${g.toName}`:'');if(g.persisted===false)return`${n}${party?' · '+party:''} · Registered PO${g.registeredItemCount?` · ${g.registeredItemCount} item(s)`:''}`;return`${n}${party?' · '+party:''} · ${g.batchCount||0} movement batch(es)`;}
function referenceMeta(){const a=action();if(a.refType==='internal_transfer')return{title:'Internal Transfer Group',group:'Transfer Group',note:'One Internal Transfer No. can contain multiple warehouse-transfer batches.'};if(a.refType==='receiving_no')return{title:'Receiving Group',group:'Receiving Group',note:'One Receiving No. can contain multiple client-return batches.'};if(a.refType==='wellora_po')return{title:'Wellora PO Movement Group',group:'PO Group',note:'Registered Wellora POs are available here automatically. Reuse the registered PO instead of entering it again.'};return{title:'PO Movement Group',group:'PO Group',note:'One PO can contain multiple movement batches.'};}
function referenceHtml(){const a=action(),m=referenceMeta(),list=groupCandidates();return`<section class="border border-cyan-900/50 rounded-xl p-3 space-y-3"><div class="font-semibold text-sm text-cyan-300">${m.title}</div><div class="grid sm:grid-cols-[220px_420px] gap-2 items-end">${field(m.group,`<select id="bmGroupMode" class="${cls} mt-1"><option value="new">New ${a.refLabel}</option><option value="existing">Existing ${a.refLabel}</option></select>`)}<label id="bmExistingWrap" class="hidden block min-w-0 text-xs text-slate-400">Existing ${a.refLabel}<select id="bmExistingGroup" class="${cls} mt-1"><option value="">-- Select Existing --</option>${list.map(g=>`<option value="${esc(g.id)}">${esc(groupLabel(g))}</option>`).join('')}</select></label></div><div id="bmNewRefWrap" class="max-w-xs">${field(a.refLabel,`<input id="bmReference" class="${cls} mt-1" placeholder="${a.refLabel}">`)}</div><div id="bmGroupInfo" class="text-[11px] text-slate-500">${m.note}</div></section>`;}
function reservationHtml(){if(action().to!=='client')return'';const rs=reservationRecords();return`<section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-2">Reservation (Optional)</div>${field('Reservation',`<select id="bmReservation" class="${cls} mt-1"><option value="">No Reservation</option>${rs.map(r=>`<option value="${r.id}">${esc(r.reservation.clientName||'')} · ${esc(r.reservation.reference||'PO pending')} · ${r.total} reserved</option>`).join('')}`,'max-w-xl')}<div id="bmReservationInfo" class="text-[11px] text-slate-500 mt-2">Select a reservation to automatically add the exact reserved balances. Reserved quantity is not treated as ordinary Available stock.</div></section>`;}
function logisticsHtml(){return`<section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-3">Logistics</div><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">${field('Logistics Provider',`<select id="bmLogisticsProvider" class="${cls} mt-1"><option value="">Optional / Internal</option>${logisticsProviders().map(x=>`<option value="${x.id}" data-name="${esc(partyName(x))}">${esc(partyName(x))}</option>`).join('')}</select>`)}${field('Contact Person',`<input id="bmContactPerson" class="${cls} mt-1">`)}${field('Contact Number',`<input id="bmContactNumber" class="${cls} mt-1">`)}${field('Transport / Vessel No.',`<input id="bmTransportNo" class="${cls} mt-1">`)}${field('Logistics / Delivery Reference',`<input id="bmLogisticsRef" class="${cls} mt-1">`)}${field('ETA / Movement Date',`<input id="bmMovementDate" type="date" class="${cls} mt-1">`)}${field('Delivery Ticket / DO',`<input id="bmDeliveryTicket" class="${cls} mt-1">`)}${field('Receiving Ticket',`<input id="bmReceivingTicket" class="${cls} mt-1">`)}</div></section>`;}
function commercialHtml(){if(action().to!=='client')return'';return`<section class="border border-emerald-900/50 rounded-xl p-3"><div class="font-semibold text-sm text-emerald-400 mb-3">Client Commercial / Rental</div><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">${field('PO Total Amount',`<input id="bmPOAmount" type="number" min="0" step="0.01" class="${cls} mt-1">`)}${field('Currency',`<input id="bmCurrency" value="MYR" class="${cls} mt-1">`)}${field('Use From',`<input id="bmPeriodFrom" type="date" class="${cls} mt-1">`)}${field('Due / Use To',`<input id="bmPeriodTo" type="date" class="${cls} mt-1">`)}</div></section>`;}
function formHtml(defaultAction='DELIVER_CLIENT'){const a=ACTIONS[defaultAction];return`<form id="batchMoveForm" data-ims-movement-module="11" class="space-y-4"><section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-3">Movement</div><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">${field('Movement Type',`<select id="bmAction" class="${cls} mt-1">${Object.entries(ACTIONS).map(([k,v])=>`<option value="${k}" ${k===defaultAction?'selected':''}>${v.label}</option>`).join('')}</select>`)}${field(a.from==='warehouse'?'Source Warehouse':a.from==='supplier'?'Source Supplier':'Source Client',`<select id="bmSource" class="${cls} mt-1"></select>`)}${field(a.to==='warehouse'?'Destination Warehouse':'Destination Client',`<select id="bmDestination" class="${cls} mt-1"></select>`)}</div></section><div id="bmReferenceWrap"></div><div id="bmCommercialWrap"></div><div id="bmReservationWrap"></div><section class="border border-slate-800 rounded-xl p-3 space-y-3"><div><div class="font-semibold text-sm">Movement Items</div><div class="text-[11px] text-slate-500">Use Exact Find & Add when you know the full identity, or use Loose Search below for a serial prefix, partial description, or category.</div></div><div class="grid lg:grid-cols-[170px_minmax(0,1fr)_auto] gap-2 items-end">${field('Find By',`<select id="bmLookupField" class="${cls} mt-1"><option value="alias">Wellora SN / R2R SN</option><option value="name">Description</option></select>`)}${field('Exact Value',`<input id="bmLookupValue" class="${cls} mt-1" placeholder="Enter exact value">`)}<button id="bmFindItem" type="button" class="bg-cyan-700 px-4 py-2.5 rounded-lg text-sm font-bold">Find & Add</button></div><div class="border border-cyan-900/40 rounded-xl p-3 space-y-3"><div><div class="font-semibold text-sm text-cyan-300">Loose Search</div><div class="text-[11px] text-slate-500">Example: type ABD-123- to show eligible serial numbers beginning with ABD-123-.</div></div><div class="grid sm:grid-cols-[minmax(0,1fr)_220px_auto] gap-2 items-end">${field('SN Prefix / Description',`<input id="bmLooseValue" class="${cls} mt-1" placeholder="SN prefix or part of description">`)}${field('Category',`<select id="bmLooseCategory" class="${cls} mt-1">${looseCategoryOptions()}</select>`)}<button id="bmLooseSearch" type="button" class="bg-cyan-800 hover:bg-cyan-700 px-4 py-2.5 rounded-lg text-sm font-bold">Search</button></div><div id="bmLooseResults" class="text-xs text-slate-500">Enter a SN prefix / partial description, or choose a category.</div></div><div id="bmLines" class="space-y-2"></div></section>${logisticsHtml()}${field('Remark',`<textarea id="bmRemark" rows="2" class="${cls} mt-1"></textarea>`)}<button id="bmSave" class="w-full bg-red-600 py-3 rounded-lg text-sm font-bold">Start Movement</button></form>`;}
function syncTop(){const a=action(),s=$('bmSource'),d=$('bmDestination');if(!s||!d)return;s.innerHTML=options(sourceList(),'Source');d.innerHTML=options(destinationList(),'Destination');const sl=s.closest('label'),dl=d.closest('label');if(sl)sl.childNodes[0].textContent=a.from==='warehouse'?'Source Warehouse':a.from==='supplier'?'Source Supplier':'Source Client';if(dl)dl.childNodes[0].textContent=a.to==='warehouse'?'Destination Warehouse':'Destination Client';clearItems();}
function bindReference(){const mode=$('bmGroupMode'),existing=$('bmExistingGroup');if(!mode)return;const apply=()=>{const ex=mode.value==='existing';$('bmExistingWrap')?.classList.toggle('hidden',!ex);$('bmNewRefWrap')?.classList.toggle('hidden',ex);if(ex)applyExistingGroup();};mode.onchange=apply;if(existing)existing.onchange=applyExistingGroup;apply();}
function applyExistingGroup(){const g=groups.find(x=>x.id===$('bmExistingGroup')?.value);if(!g)return;const a=action(),s=$('bmSource'),d=$('bmDestination');if($('bmReference'))$('bmReference').value=groupNumber(g);if(a.refType==='internal_transfer'){if(g.fromId&&[...s.options].some(o=>o.value===g.fromId))s.value=g.fromId;if(g.toId){d.innerHTML=options(destinationList(),'Destination');if([...d.options].some(o=>o.value===g.toId))d.value=g.toId;}}else if(g.partyId){if(a.from==='supplier'||a.from==='client'){if([...s.options].some(o=>o.value===g.partyId))s.value=g.partyId;d.innerHTML=options(destinationList(),'Destination');}else if(a.to==='client'&&[...d.options].some(o=>o.value===g.partyId))d.value=g.partyId;}if($('bmGroupInfo'))$('bmGroupInfo').textContent=g.persisted===false?`Registered ${a.refLabel} ${groupNumber(g)} · ${g.registeredItemCount||0} registered item(s) · first Movement batch will reuse this PO.`:`Existing ${a.refLabel} ${groupNumber(g)} · ${g.batchCount||0} prior movement batch(es).`;clearItems();}
function renderDynamic(){$('bmReferenceWrap').innerHTML=referenceHtml();$('bmCommercialWrap').innerHTML=commercialHtml();$('bmReservationWrap').innerHTML=reservationHtml();bindReference();if($('bmReservation'))$('bmReservation').onchange=()=>applyReservation().catch(e=>alert('Unable to load reservation items: '+(e?.message||e)));}
async function applyReservation(){const rr=selectedReservation(),s=$('bmSource'),d=$('bmDestination'),info=$('bmReservationInfo');clearItems();if(!rr){if(info)info.textContent='Select a reservation to automatically add its reserved items.';return;}const r=rr.reservation;if(r.locationId&&[...s.options].some(o=>String(o.value)===String(r.locationId)))s.value=String(r.locationId);else if(r.locationName){const o=[...s.options].find(o=>norm(o.dataset?.name||o.textContent)===norm(r.locationName));if(o)s.value=o.value;}if(r.clientId&&[...d.options].some(o=>String(o.value)===String(r.clientId)))d.value=String(r.clientId);if($('bmReference')&&r.reference&&$('bmGroupMode')?.value==='new')$('bmReference').value=r.reference;let added=0,skipped=[];for(const line of rr.lines){if(!line.item.id){skipped.push(line.item.alias||line.item.itemCode||'Unknown item');continue;}const snap=await getDoc(doc(db,'inventory',line.item.id));if(!snap.exists()){skipped.push(line.item.alias||line.item.itemCode||line.item.id);continue;}const item={id:snap.id,...snap.data()};cacheItem(item);if(!eligibleBalance(item)){inventory=inventory.filter(x=>x.id!==item.id);skipped.push(item.alias||item.itemCode||item.name||item.id);continue;}addItem(item,line.qty);added++;}if(info)info.textContent=`Reserved ${rr.total} across ${rr.lines.length} item line(s) for ${r.clientName||'client'}. ${added} exact reserved line(s) added${skipped.length?` · ${skipped.length} unavailable/changed`:''}.`;if(!added&&rr.lines.length)throw new Error('Reservation was found, but none of its reserved balances are currently eligible at the reserved source. Refresh Reservation or check stock state.');}
async function changeAction(){const current=$('bmAction').value,form=$('batchMoveForm'),remark=$('bmRemark')?.value||'';form.outerHTML=formHtml(current);$('bmRemark').value=remark;bindForm();syncTop();await loadGroupsForAction();renderDynamic();}
function bindForm(){$('bmAction').onchange=()=>changeAction().catch(e=>alert('Unable to change movement type: '+(e?.message||e)));$('bmSource').onchange=()=>{$('bmDestination').innerHTML=options(destinationList(),'Destination');clearItems();};$('bmDestination').onchange=clearItems;$('bmFindItem').onclick=()=>findItem().catch(e=>alert('Item lookup failed: '+(e?.message||e)));$('bmLookupValue').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();findItem().catch(err=>alert('Item lookup failed: '+(err?.message||err)));}};$('bmLooseSearch').onclick=()=>looseSearch();$('bmLooseValue').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();looseSearch();}};$('bmLooseCategory').onchange=()=>looseSearch();$('batchMoveForm').onsubmit=save;}
function collect(){return[...document.querySelectorAll('.bmLine')].map(r=>{const item=inventory.find(x=>x.id===r.dataset.itemId),b=item?eligibleBalance(item):null,qty=Number(r.querySelector('.bmQty')?.value||0);return{item,b,qty};}).filter(x=>x.item&&x.b);}
async function resolveGroup(){const a=action(),mode=$('bmGroupMode')?.value||'new',s=source(),d=destination();if(mode==='existing'){const g=groups.find(x=>x.id===$('bmExistingGroup')?.value);if(!g)throw new Error(`Select an existing ${a.refLabel}.`);if(g.persisted===false){const ref=doc(db,'movement_groups',`reg-${g.registrationBatchId}`);return{...g,id:ref.id,ref,existing:false,reference:groupNumber(g)};}return{...g,ref:doc(db,'movement_groups',g.id),existing:true,reference:groupNumber(g)};}const reference=$('bmReference')?.value.trim()||'';if(!reference)throw new Error(`${a.refLabel} is required.`);const party=a.from==='supplier'||a.from==='client'?s:a.to==='client'?d:null;const dup=groups.find(g=>groupMatches(g,a)&&norm(groupNumber(g))===norm(reference)&&(a.refType==='internal_transfer'||norm(g.partyId)===norm(party?.id||'')));if(dup)throw new Error(`${a.refLabel} already exists. Select Existing ${a.refLabel}.`);const ref=doc(collection(db,'movement_groups'));return{id:ref.id,ref,existing:false,reference,partyId:party?.id||'',partyName:party?.name||'',batchCount:0,status:'open'};}
async function save(e){e.preventDefault();if(saving||!can('movement.add'))return;try{rememberMovement();const a=action(),s=source(),d=destination(),lines=collect(),g=await resolveGroup(),rr=a.to==='client'?selectedReservation():null;if(!s||!d||!lines.length)throw new Error('Complete source, destination and add at least one item.');if(a.from===a.to&&String(s.id)===String(d.id))throw new Error('Source and destination must be different.');if(rr&&String(rr.reservation.clientId||'')!==String(d.id))throw new Error('Selected Reservation belongs to a different Client.');for(const l of lines){const max=singleItem(l.item)?1:l.b.qty;if(!Number.isInteger(l.qty)||l.qty<1||l.qty>max)throw new Error(`${l.item.alias||l.item.itemCode}: invalid quantity.`);}const poAmount=$('bmPOAmount')?.value===''||!$('bmPOAmount')?null:Number($('bmPOAmount').value),currency=$('bmCurrency')?.value||'',periodFrom=$('bmPeriodFrom')?.value||'',periodTo=$('bmPeriodTo')?.value||'';if(poAmount!==null&&(!Number.isFinite(poAmount)||poAmount<0))throw new Error('PO Total Amount must be valid.');if((periodFrom&&!periodTo)||(!periodFrom&&periodTo)||(periodTo&&periodTo<periodFrom))throw new Error('Check rental dates.');const lp=$('bmLogisticsProvider'),logisticsProviderId=lp?.value||'',logisticsProviderName=lp?.selectedOptions?.[0]?.dataset?.name||'',contactPerson=$('bmContactPerson')?.value.trim()||'',contactNumber=$('bmContactNumber')?.value.trim()||'',transportNo=$('bmTransportNo')?.value.trim()||'',logisticsReference=$('bmLogisticsRef')?.value.trim()||'',movementDate=$('bmMovementDate')?.value||'',deliveryTicket=$('bmDeliveryTicket')?.value.trim()||'',receivingTicket=$('bmReceivingTicket')?.value.trim()||'',remark=$('bmRemark')?.value.trim()||'';saving=true;const btn=$('bmSave');btn.disabled=true;btn.textContent='Saving...';const u=auth.currentUser,p=await getDoc(doc(db,'users',u.uid));if(!p.exists()||p.data().status!=='active')throw new Error('Active user required.');const user=p.data(),email=user.email||u.email||'',batchId=doc(collection(db,'movements')).id,at=now(),movementRefs=lines.map(()=>doc(collection(db,'movements'))),actualByItem=new Map();for(const l of lines)actualByItem.set(l.item.id,(actualByItem.get(l.item.id)||0)+l.qty);let reservationAudit=null;
 await runTransaction(db,async tx=>{const ids=new Set(lines.map(l=>l.item.id));if(rr)for(const x of rr.lines)ids.add(x.item.id);const state=new Map();for(const id of ids){const r=doc(db,'inventory',id),snap=await tx.get(r);if(!snap.exists())throw new Error('Item missing.');state.set(id,{ref:r,data:snap.data(),balances:balances(snap.data())});}
 let reservedTotal=0;if(rr){for(const x of rr.lines){const st=state.get(x.item.id),active=st.data.activeReservation;if(!active||String(active.reservationId||'')!==String(rr.id))throw new Error(`${x.item.alias||x.item.itemCode}: reservation changed.`);const lineReserved=Number(active.lineQty||x.qty||0);let released=0;for(const b of st.balances.filter(b=>b.status==='Reserved'&&String(b.reservationId||'')===String(rr.id))){const q=b.qty;b.qty=0;let dst=st.balances.find(v=>v!==b&&v.status==='Available'&&v.locationType===b.locationType&&v.locationId===b.locationId&&v.locationName===b.locationName);dst?dst.qty+=q:st.balances.push({qty:q,locationType:b.locationType,locationId:b.locationId||'',locationName:b.locationName,status:'Available'});released+=q;}if(released<lineReserved)throw new Error(`${x.item.alias||x.item.itemCode}: reserved stock changed.`);reservedTotal+=lineReserved;}}
 const sourceStatus=a.from==='supplier'?'At Supplier':a.from==='client'?'At Client':'Available';const movementPayloads=[];for(let n=0;n<lines.length;n++){const l=lines[n],st=state.get(l.item.id),target={locationType:a.from,locationId:s.id,locationName:s.name};let remaining=l.qty;for(const b of st.balances.filter(b=>b.status===sourceStatus&&b.locationType===target.locationType&&((target.locationId&&String(b.locationId)===String(target.locationId))||norm(b.locationName)===norm(target.locationName)))){const take=Math.min(b.qty,remaining);b.qty-=take;remaining-=take;if(!remaining)break;}if(remaining>0)throw new Error(`${l.item.alias||l.item.itemCode}: insufficient source stock.`);const mr=movementRefs[n];st.balances.push({qty:l.qty,locationType:'transit',locationId:mr.id,locationName:`Transit to ${d.name}`,status:'In Transit'});movementPayloads.push({ref:mr,data:{movementId:mr.id,movementBatchId:batchId,movementGroupId:g.id,referenceType:a.refType,referenceLabel:a.refLabel,referenceNumber:g.reference,itemId:l.item.id,itemCode:l.item.itemCode,itemAlias:l.item.alias||'',itemNameSnapshot:l.item.name,action:$('bmAction').value,actionLabel:a.label,fromType:a.from,fromId:s.id,fromName:s.name,toType:a.to,toId:d.id,toName:d.name,toStatus:a.toStatus,qty:l.qty,unit:l.item.unit||'',remark,status:'in_transit',createdAt:at,createdBy:email,createdByRole:user.role||window.IMS_ROLE||'',clientPOAmount:a.refType==='client_po'?poAmount:null,currency:a.refType==='client_po'?currency:'',reservationId:rr?.id||'',periodFrom,periodTo,logisticsProviderId,logisticsProviderName,contactPerson,contactNumber,transportNo,logisticsReference,movementDate,deliveryTicket,receivingTicket}});}
 const inventoryWrites=[],deltas=[];for(const[id,st]of state){const clean=st.balances.filter(b=>b.qty>0),sum=summary(clean),patch={stockBalances:clean,status:sum.status,currentLocation:sum.location,lastEditedBy:email,lastEditedAt:at};if(rr&&rr.lines.some(x=>x.item.id===id)){const active=st.data.activeReservation,lineReserved=Number(active?.lineQty||0),actual=actualByItem.get(id)||0;patch.activeReservation=null;patch.lastReservation={...active,status:'Fulfilled',fulfilledAt:at,fulfilledBy:email,actualMovedQty:actual,reservedUsed:Math.min(lineReserved,actual),releasedBack:Math.max(0,lineReserved-actual),extraAvailableUsed:Math.max(0,actual-lineReserved),movementBatchId:batchId};}inventoryWrites.push({ref:st.ref,patch});deltas.push(inventorySummaryDelta(st.data,{...st.data,...patch}));}
 await applyInventorySummaryDelta(tx,combineInventorySummaryDeltas(deltas),{updatedAt:at,updatedBy:email});
 for(const w of movementPayloads)tx.set(w.ref,w.data);for(const w of inventoryWrites)tx.update(w.ref,w.patch);const groupPatch={movementGroupId:g.id,referenceType:a.refType,referenceLabel:a.refLabel,referenceNumber:g.reference,partyId:g.partyId||'',partyName:g.partyName||'',status:'open',batchCount:g.existing?Number(g.batchCount||0)+1:1,updatedAt:at,lastBatchId:batchId,fromId:s.id,fromName:s.name,toId:d.id,toName:d.name};if(!g.existing){groupPatch.createdAt=at;groupPatch.createdBy=email;}tx.set(g.ref,groupPatch,{merge:true});if(rr){reservationAudit={reservationId:rr.id,reservedQty:reservedTotal,actualQty:[...actualByItem.values()].reduce((n,q)=>n+q,0),releasedBack:Math.max(0,reservedTotal-[...actualByItem.values()].reduce((n,q)=>n+q,0)),extraAvailableUsed:Math.max(0,[...actualByItem.values()].reduce((n,q)=>n+q,0)-reservedTotal)};tx.set(doc(db,'reservation_events',rr.id),{status:'Fulfilled',fulfilledAt:at,fulfilledBy:email,movementBatchId:batchId,movementGroupId:g.id,actualMovedQty:reservationAudit.actualQty,reservedUsed:Math.min(reservedTotal,reservationAudit.actualQty),releasedBack:reservationAudit.releasedBack,extraAvailableUsed:reservationAudit.extraAvailableUsed},{merge:true});}});
 for(let n=0;n<lines.length;n++){const l=lines[n],mr=movementRefs[n];await addDoc(collection(db,'operational_logs'),{logVersion:3,date:at,activity:$('bmAction').value,activityLabel:a.label,status:'In Transit',movementGroupId:g.id,movementBatchId:batchId,movementId:mr.id,referenceType:a.refType,referenceNumber:g.reference,fromType:a.from,fromName:s.name,toType:a.to,toName:d.name,qty:l.qty,unit:l.item.unit||'',itemId:l.item.id,itemCode:l.item.itemCode,itemAlias:l.item.alias||'',itemName:l.item.name,clientId:a.to==='client'?d.id:a.from==='client'?s.id:'',clientName:a.to==='client'?d.name:a.from==='client'?s.name:'',supplierId:a.from==='supplier'?s.id:'',supplierName:a.from==='supplier'?s.name:'',logisticsProviderId,logisticsProviderName,contactPerson,contactNumber,transportNo,logisticsReference,movementDate,deliveryTicket,receivingTicket,performedBy:email,performedByRole:user.role||window.IMS_ROLE||'',remark});}
 await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType:'START_MOVEMENT_BATCH',module:'Movement',targetType:'movement_batch',targetName:`${g.reference} · ${a.label} · ${lines.length} line(s)`,targetId:batchId,summary:`Start Movement Batch under ${a.refLabel} ${g.reference}`,beforeValue:rr?{reservationId:rr.id,reservedQty:rr.total}:null,afterValue:{movementGroupId:g.id,referenceType:a.refType,referenceNumber:g.reference,company:g.partyName||'',source:s.name,destination:d.name,reservation:reservationAudit,lines:lines.map(l=>({itemIdentity:l.item.alias||'',imsItemId:l.item.itemCode,qty:l.qty}))},changedFields:['movementGroupId','referenceNumber','source','destination','lines','logistics'],remark,performedBy:email,performedByRole:user.role||window.IMS_ROLE||'',performedAt:at});alert(`${lines.length} movement line(s) started under ${a.refLabel} ${g.reference}.`);location.reload();}catch(err){alert('Movement failed: '+(err?.message||err));saving=false;const btn=$('bmSave');if(btn){btn.disabled=false;btn.textContent='Start Movement';}}}
async function arriveMovement(id){if(!can('movement.edit'))return;rememberMovement();const email=auth.currentUser?.email||'',at=now(),movementRef=doc(db,'movements',id);await runTransaction(db,async tx=>{const movementSnap=await tx.get(movementRef);if(!movementSnap.exists())throw new Error('Movement missing.');const m={id:movementSnap.id,...movementSnap.data()};if(m.status!=='in_transit')throw new Error('Movement is no longer in transit.');const ref=doc(db,'inventory',m.itemId),snap=await tx.get(ref);if(!snap.exists())throw new Error('Item missing.');const before=snap.data(),bal=balances(before),tr=bal.find(b=>b.locationType==='transit'&&b.locationId===m.movementId);if(!tr||tr.qty<m.qty)throw new Error('Transit balance missing.');tr.qty-=m.qty;let dst=bal.find(b=>b.locationType===m.toType&&((m.toId&&String(b.locationId)===String(m.toId))||norm(b.locationName)===norm(m.toName)));if(dst){dst.qty+=m.qty;dst.status=m.toStatus;}else bal.push({qty:m.qty,locationType:m.toType,locationId:m.toId||'',locationName:m.toName,status:m.toStatus});const clean=bal.filter(x=>x.qty>0),sum=summary(clean),patch={stockBalances:clean,status:sum.status,currentLocation:sum.location,lastEditedBy:email,lastEditedAt:at};await applyInventorySummaryDelta(tx,inventorySummaryDelta(before,{...before,...patch}),{updatedAt:at,updatedBy:email});tx.update(ref,patch);tx.update(movementRef,{status:'arrived',arrivedAt:at,arrivedBy:email});});location.reload();}
async function mount(){if(!can('movement.view'))return;const core=$('moveForm');if(!core||$('batchMoveForm'))return;try{await load();}catch(err){console.error('IMS Movement load failed:',err);core.innerHTML=`<div class="border border-red-900 rounded-xl p-3 text-xs text-red-300">Unable to load Movement: ${esc(err?.message||err)}</div>`;return;}const w=document.createElement('div');w.innerHTML=formHtml('DELIVER_CLIENT');core.replaceWith(w.firstElementChild);bindForm();syncTop();renderDynamic();}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>mount().catch(console.error),35);}).observe(document.body,{childList:true,subtree:true});mount().catch(console.error);window.arriveMovement=arriveMovement;window.IMSMovement=Object.freeze({mount,load,arriveMovement,applyReservation});window.dispatchEvent(new CustomEvent('ims:movement-ready'));export{mount,load,arriveMovement};