import { auth, db } from '../../firebase-config.js';
import { collection, addDoc, getDocs, doc, updateDoc, query, orderBy } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';

const inputCls='w-full min-w-0 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-red-500';
const MASTER_GROUPS=Object.freeze([
  {type:'warehouse',label:'Warehouses'},
  {type:'item_type',label:'Item Types',special:'itemType'},
  {type:'unit',label:'Units'},
  {type:'category',label:'Categories'},
  {type:'size',label:'Sizes'},
  {type:'grade',label:'Grades'},
  {type:'ppf',label:'PPF'},
  {type:'connection',label:'Connections'},
  {type:'range',label:'Ranges'},
  {type:'weight_unit',label:'Weight Units'},
  {type:'brand',label:'Brands'}
]);
let settings=[];
const byId=id=>document.getElementById(id);
const nowISO=()=>new Date().toISOString();
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(title,body)=>`<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><h2 class="font-bold text-sm sm:text-base mb-4">${title}</h2>${body}</section>`;

async function reload(){const snap=await getDocs(query(collection(db,'settings'),orderBy('value','asc')));settings=snap.docs.map(d=>({id:d.id,...d.data()}));return settings;}
function itemsFor(type){return settings.filter(x=>x.type===type);}
async function writeAudit(actionType,targetType,targetName,beforeValue=null,afterValue=null,remark='',targetId=''){const user=auth.currentUser;if(!user)return;await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType,module:'Global Settings',targetType,targetName:String(targetName||''),targetId:String(targetId||''),summary:`${String(actionType||'').replace(/_/g,' ')}: ${targetName||targetType}`,beforeValue,afterValue,changedFields:[],remark:String(remark||''),metadata:{source:'masters-module'},performedBy:window.IMSUser?.email||user.email||'',performedByRole:window.IMS_ROLE||'',performedAt:nowISO()});}

function itemTypeForm(){return `<form class="imsMasterForm grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2 items-end mb-3" data-type="item_type" data-special="itemType"><label class="text-[11px] text-slate-400 lg:col-span-2">Item Type Name<input class="imsMasterInput ${inputCls} mt-1" required placeholder="Item Type name"></label><label class="text-[11px] text-slate-400">Quantity Behaviour<select class="imsItemTypeQtyMode ${inputCls} mt-1"><option value="single">Single item — Qty locked at 1</option><option value="flexible">Flexible quantity</option></select></label><label class="text-[11px] text-slate-400">Default Qty<input class="imsItemTypeDefaultQty ${inputCls} mt-1" type="number" min="1" step="1" value="1"></label><button class="sm:col-span-2 lg:col-span-4 w-full bg-red-600 px-4 py-2.5 rounded-lg text-xs font-bold">Add Item Type</button></form>`;}
function masterCard(group){const editable=can('masters.add'),statusable=can('masters.status'),rows=itemsFor(group.type),singular=group.label.replace(/s$/,'');const form=!editable?'<div class="text-[11px] text-slate-500 mb-3">View only for this role.</div>':group.special==='itemType'?itemTypeForm():`<form class="imsMasterForm grid grid-cols-[minmax(0,1fr)_auto] gap-2 items-end mb-3" data-type="${group.type}"><input class="imsMasterInput ${inputCls}" required placeholder="Add ${esc(singular)}"><button class="bg-red-600 px-4 py-2.5 rounded-lg text-xs font-bold min-w-24">Add</button></form>`;return card(group.label,`<p class="text-[11px] text-slate-500 mb-3">Values are never deleted. Deactivate obsolete values so historical records remain traceable.</p>${group.special==='itemType'?'<p class="text-[11px] text-cyan-300 mb-3">Item Type controls Registration Qty behaviour. All registrations still create one permanent IMS record per physical unit.</p>':''}${form}<div class="space-y-2">${rows.map(x=>`<div class="bg-slate-950 border border-slate-800 rounded-lg p-2 flex justify-between items-center gap-3"><div class="min-w-0"><span class="text-sm break-words">${esc(x.value)}</span>${group.special==='itemType'?`<div class="text-[10px] text-slate-500">${x.quantityMode==='single'?'Single item · Qty 1':`Flexible · Default Qty ${Number(x.defaultQty||1)}`}</div>`:''} <span class="text-[10px] ${x.status==='inactive'?'text-amber-400':'text-emerald-400'}">${esc(x.status||'active')}</span></div>${statusable?`<button data-master-toggle="${x.id}" data-master-type="${group.type}" class="bg-slate-700 px-2 py-1 rounded text-[10px] shrink-0">${x.status==='inactive'?'Activate':'Deactivate'}</button>`:''}</div>`).join('')||'<div class="text-xs text-slate-500">No records.</div>'}</div>`);}
function setHeader(){if(byId('pageTitle'))byId('pageTitle').textContent='Global Settings';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Warehouses, item types, units and registration masters · Firestore ordered.';document.querySelectorAll('.navBtn[data-tab]').forEach(btn=>{btn.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${btn.dataset.tab==='settings'?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`;});}
function render(){const mount=byId('appContent');if(!mount||!can('masters.view'))return;setHeader();mount.innerHTML=`<div id="imsMastersModule" class="w-full space-y-5">${card('Global Settings',`<p class="text-sm text-slate-300">Registration and operational values are managed here and selected in the working modules.</p><p class="text-xs text-slate-500 mt-2">Reference masters are intentionally loaded completely because operational forms need the full selectable set. Ordering is performed by Firestore.</p>`)}<div class="space-y-5">${MASTER_GROUPS.map(masterCard).join('')}</div><div id="imsBackupRecoveryHost"></div></div>`;mount.querySelectorAll('.imsMasterForm').forEach(form=>form.onsubmit=createMaster);mount.querySelectorAll('[data-master-toggle]').forEach(btn=>btn.onclick=()=>toggleMaster(btn.dataset.masterToggle,btn.dataset.masterType));if(window.IMSBackup?.mount)window.IMSBackup.mount();else window.addEventListener('ims:backup-ready',()=>window.IMSBackup?.mount?.(),{once:true});}
async function createMaster(e){e.preventDefault();if(!can('masters.add'))return;const form=e.currentTarget,type=form.dataset.type,input=form.querySelector('.imsMasterInput'),value=input.value.trim().replace(/\s+/g,' ');if(!value)return;if(settings.some(x=>x.type===type&&norm(x.value)===norm(value))){alert('This value already exists. Activate the existing record if needed.');return;}const extra={};if(type==='item_type'){extra.quantityMode=form.querySelector('.imsItemTypeQtyMode')?.value==='single'?'single':'flexible';extra.defaultQty=extra.quantityMode==='single'?1:Math.max(1,Number(form.querySelector('.imsItemTypeDefaultQty')?.value||1));}const ref=await addDoc(collection(db,'settings'),{type,value,normalizedValue:norm(value),status:'active',...extra,createdAt:nowISO(),createdBy:window.IMSUser?.email||auth.currentUser?.email||''});await writeAudit('CREATE_MASTER',type,value,null,{value,status:'active',...extra},'',ref.id);await reload();render();}
async function toggleMaster(id,type){if(!can('masters.status'))return;const x=settings.find(s=>s.id===id);if(!x)return;const status=x.status==='inactive'?'active':'inactive',reason=prompt(`Reason for ${status==='inactive'?'deactivating':'activating'} ${x.value} (required)`,'');if(!reason?.trim())return;await updateDoc(doc(db,'settings',id),{status,updatedAt:nowISO(),updatedBy:window.IMSUser?.email||auth.currentUser?.email||''});await writeAudit('CHANGE_MASTER_STATUS',type,x.value,{status:x.status||'active'},{status},reason.trim(),id);await reload();render();}
function interceptNavigation(){document.addEventListener('click',async event=>{const btn=event.target.closest?.('.navBtn[data-tab="settings"]');if(!btn||!can('masters.view'))return;event.preventDefault();event.stopImmediatePropagation();try{await reload();render();}catch(error){console.error('IMS masters module failed:',error);}},true);}
interceptNavigation();window.IMSMasters=Object.freeze({reload,render,groups:MASTER_GROUPS});window.dispatchEvent(new CustomEvent('ims:masters-ready'));export {reload,render,MASTER_GROUPS};