import {auth,db} from '../../firebase-config.js';
import {collection,doc,getDocs,limit,query,runTransaction,where} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import {applyInventorySummaryDelta,inventorySummaryDelta} from '../inventory/inventory-summary.js';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString();
const cls='w-full min-w-0 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm';
let busy=false,incidentCandidate=null,dispositionCandidate=null;

function isSuperadmin(){return String(window.IMS_ROLE||'').toLowerCase()==='superadmin';}
function email(){return auth.currentUser?.email||window.IMSUser?.email||'';}
function balances(i){return(Array.isArray(i?.stockBalances)?i.stockBalances:[]).filter(b=>Number(b.qty||0)>0).map(b=>({...b,qty:Number(b.qty||0),locationType:b.locationType||'',locationId:b.locationId||'',locationName:b.locationName||b.location||i?.currentLocation||'Unknown',status:b.status||'Not Available'}));}
function activeStatus(type){return type==='warehouse'?'Available':type==='client'?'At Client':type==='supplier'?'At Supplier':'Not Available';}
function itemStatus(list){const p=list.filter(x=>x.qty>0),order=['At Client','At Supplier','Available','Not Available'];return order.find(s=>p.some(x=>x.status===s))||p[0]?.status||'Not Available';}

async function exactItem(field,value){const snap=await getDocs(query(collection(db,'inventory'),where(field,'==',value),limit(2)));if(!snap.size)throw new Error('No exact item found.');if(snap.size>1)throw new Error('More than one item matched. Use IMS Item ID.');const d=snap.docs[0];return{id:d.id,...d.data()};}
function card(item,type){if(!item)return'<div class="text-xs text-slate-500">Find an exact item first.</div>';const eligible=type==='incident'?Boolean(item.activeIncident||['Missing','Stolen'].includes(item.status)):Boolean(item.disposition);return`<div class="border ${eligible?'border-emerald-900/60':'border-amber-900/60'} rounded-xl p-3"><b class="text-cyan-300">${esc(item.alias||item.itemCode||item.id)}</b> · ${esc(item.name||'')}<div class="text-[10px] text-slate-500 font-mono">${esc(item.itemCode||item.id)}</div><div class="text-xs text-slate-400 mt-1">${esc(item.status||'')} · ${esc(item.currentLocation||'')}</div>${eligible?`<button id="rev${type==='incident'?'Incident':'Disposition'}Btn" class="mt-3 bg-red-700 hover:bg-red-600 px-4 py-2 rounded-lg text-xs font-bold">Reverse ${type==='incident'?'Incident':'Disposition'}</button>`:`<div class="mt-3 text-xs text-amber-300">No active ${type==='incident'?'Incident':'Disposition'} found on this item.</div>`}</div>`;}
function renderCards(){if($('revIncidentResult')){$('revIncidentResult').innerHTML=card(incidentCandidate,'incident');const b=$('revIncidentBtn');if(b)b.onclick=requestIncident;}if($('revDispositionResult')){$('revDispositionResult').innerHTML=card(dispositionCandidate,'disposition');const b=$('revDispositionBtn');if(b)b.onclick=requestDisposition;}}

async function find(type){const prefix=type==='incident'?'revIncident':'revDisposition',field=$(`${prefix}Field`)?.value||'alias',value=$(`${prefix}Value`)?.value.trim()||'';if(!value)return alert('Enter an exact item value.');try{const item=await exactItem(field,value);if(type==='incident')incidentCandidate=item;else dispositionCandidate=item;renderCards();}catch(e){if(type==='incident')incidentCandidate=null;else dispositionCandidate=null;renderCards();alert(e?.message||e);}}

async function reverseIncident(id,remark){const at=now(),by=email(),itemRef=doc(db,'inventory',id),revRef=doc(collection(db,'reversals')),auditRef=doc(collection(db,'audit_traces')),logRef=doc(collection(db,'operational_logs'));await runTransaction(db,async tx=>{const snap=await tx.get(itemRef);if(!snap.exists())throw new Error('Item no longer exists.');const before=snap.data(),inc=before.activeIncident;if(!inc&&!['Missing','Stolen'].includes(before.status))throw new Error('No active Incident to reverse.');const old=balances(before);if(!old.length)throw new Error('Item has no stock balance to restore.');const next=old.map(b=>({...b,status:activeStatus(b.locationType)})),status=itemStatus(next),location=before.currentLocation||next[0]?.locationName||'';const after={...before,stockBalances:next,status,currentLocation:location,activeIncident:null,lastEditedAt:at,lastEditedBy:by};await applyInventorySummaryDelta(tx,inventorySummaryDelta(before,after),{updatedAt:at,updatedBy:by});tx.update(itemRef,{stockBalances:next,status,currentLocation:location,activeIncident:null,lastEditedAt:at,lastEditedBy:by,lastIncidentReversedAt:at,lastIncidentReversedBy:by,lastIncidentReversalRemark:remark});tx.set(revRef,{reversalId:revRef.id,type:'incident',originalId:id,itemId:id,itemAlias:before.alias||'',qty:next.reduce((a,b)=>a+b.qty,0),unit:before.unit||'',remark,performedAt:at,performedBy:by});tx.set(auditRef,{traceVersion:3,actionType:'REVERSE_INCIDENT',module:'Reversal',targetType:'inventory',targetName:before.alias||before.itemCode||id,targetId:id,summary:`Reverse Incident ${before.alias||before.itemCode||id}`,beforeValue:{status:before.status,incident:inc||null},afterValue:{status,activeIncident:null,reversalActionId:revRef.id},changedFields:['status','stockBalances','activeIncident'],remark,performedBy:by,performedByRole:'superadmin',performedAt:at});tx.set(logRef,{logVersion:3,date:at,module:'Reversal',activity:'REVERSE_INCIDENT',activityLabel:'Reverse Incident',status,itemId:id,itemAlias:before.alias||'',itemCode:before.itemCode||'',itemName:before.name||'',toName:location,qty:next.reduce((a,b)=>a+b.qty,0),unit:before.unit||'',remark,performedBy:by,performedByRole:'superadmin'});});}

async function reverseDisposition(id,remark){const at=now(),by=email(),itemRef=doc(db,'inventory',id),revRef=doc(collection(db,'reversals')),auditRef=doc(collection(db,'audit_traces')),logRef=doc(collection(db,'operational_logs'));await runTransaction(db,async tx=>{const snap=await tx.get(itemRef);if(!snap.exists())throw new Error('Item no longer exists.');const before=snap.data(),disp=before.disposition;if(!disp)throw new Error('No Disposition to reverse.');const old=balances(before);if(!old.length)throw new Error('Item has no stock balance to restore.');const next=old.map(b=>({...b,status:activeStatus(b.locationType)})),status=itemStatus(next),location=before.currentLocation||next[0]?.locationName||'';const after={...before,stockBalances:next,status,currentLocation:location,disposition:null,lastEditedAt:at,lastEditedBy:by};await applyInventorySummaryDelta(tx,inventorySummaryDelta(before,after),{updatedAt:at,updatedBy:by});tx.update(itemRef,{stockBalances:next,status,currentLocation:location,disposition:null,lastEditedAt:at,lastEditedBy:by,lastDispositionReversedAt:at,lastDispositionReversedBy:by,lastDispositionReversalRemark:remark});tx.set(revRef,{reversalId:revRef.id,type:'disposition',originalId:id,itemId:id,itemAlias:before.alias||'',qty:next.reduce((a,b)=>a+b.qty,0),unit:before.unit||'',remark,performedAt:at,performedBy:by});tx.set(auditRef,{traceVersion:3,actionType:'REVERSE_DISPOSITION',module:'Reversal',targetType:'inventory',targetName:before.alias||before.itemCode||id,targetId:id,summary:`Reverse Disposition ${before.alias||before.itemCode||id}`,beforeValue:{status:before.status,disposition:disp},afterValue:{status,disposition:null,reversalActionId:revRef.id},changedFields:['status','stockBalances','disposition'],remark,performedBy:by,performedByRole:'superadmin',performedAt:at});tx.set(logRef,{logVersion:3,date:at,module:'Reversal',activity:'REVERSE_DISPOSITION',activityLabel:'Reverse Disposition',status,itemId:id,itemAlias:before.alias||'',itemCode:before.itemCode||'',itemName:before.name||'',toName:location,qty:next.reduce((a,b)=>a+b.qty,0),unit:before.unit||'',remark,performedBy:by,performedByRole:'superadmin'});});}

async function requestIncident(){if(!incidentCandidate||busy)return;const remark=prompt('Incident reversal remark (required)');if(!remark?.trim())return;if(!confirm(`Reverse Incident for ${incidentCandidate.alias||incidentCandidate.itemCode}?\n\nThe current stored balance will return to active stock.`))return;busy=true;try{await reverseIncident(incidentCandidate.id,remark.trim());incidentCandidate=null;renderCards();alert('Incident reversed. Stock returned to active status.');}catch(e){alert('Incident reversal failed: '+(e?.message||e));}finally{busy=false;}}
async function requestDisposition(){if(!dispositionCandidate||busy)return;const remark=prompt('Disposition reversal remark (required)');if(!remark?.trim())return;if(!confirm(`Reverse Disposition for ${dispositionCandidate.alias||dispositionCandidate.itemCode}?\n\nThe current stored balance will return to active stock.`))return;busy=true;try{await reverseDisposition(dispositionCandidate.id,remark.trim());dispositionCandidate=null;renderCards();alert('Disposition reversed. Stock returned to active status.');}catch(e){alert('Disposition reversal failed: '+(e?.message||e));}finally{busy=false;}}

function install(){if(!isSuperadmin()||!$('revMoveSearch')||document.querySelector('[data-ims-status-reversal="1"]'))return;const host=$('appContent')?.querySelector('.space-y-5');if(!host)return;const section=document.createElement('section');section.dataset.imsStatusReversal='1';section.className='grid lg:grid-cols-2 gap-4';section.innerHTML=`<div class="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3"><div><div class="font-bold">Incident Reversal</div><div class="text-[11px] text-slate-500">Simple reversal: keep the current location/qty, return the balance to its normal active status, clear the Incident, and record the remark.</div></div><div class="grid sm:grid-cols-[150px_minmax(0,1fr)_auto] gap-2 items-end"><label class="text-xs text-slate-400">Find By<select id="revIncidentField" class="${cls} mt-1"><option value="alias">Wellora / R2R SN</option><option value="itemCode">IMS Item ID</option></select></label><label class="text-xs text-slate-400">Exact Value<input id="revIncidentValue" class="${cls} mt-1"></label><button id="revIncidentFind" class="bg-cyan-700 px-3 py-2.5 rounded-lg text-xs font-bold">Find</button></div><div id="revIncidentResult">${card(null,'incident')}</div></div><div class="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3"><div><div class="font-bold">Disposition Reversal</div><div class="text-[11px] text-slate-500">Simple reversal: keep the current location/qty, return the balance to its normal active status, clear the Disposition, and record the remark.</div></div><div class="grid sm:grid-cols-[150px_minmax(0,1fr)_auto] gap-2 items-end"><label class="text-xs text-slate-400">Find By<select id="revDispositionField" class="${cls} mt-1"><option value="alias">Wellora / R2R SN</option><option value="itemCode">IMS Item ID</option></select></label><label class="text-xs text-slate-400">Exact Value<input id="revDispositionValue" class="${cls} mt-1"></label><button id="revDispositionFind" class="bg-cyan-700 px-3 py-2.5 rounded-lg text-xs font-bold">Find</button></div><div id="revDispositionResult">${card(null,'disposition')}</div></div>`;const deleteSection=$('deleteLookupValue')?.closest('section');deleteSection?deleteSection.before(section):host.appendChild(section);$('revIncidentFind').onclick=()=>find('incident');$('revDispositionFind').onclick=()=>find('disposition');$('revIncidentValue').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();find('incident');}};$('revDispositionValue').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();find('disposition');}};}

let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,40);}).observe(document.body,{childList:true,subtree:true});window.addEventListener('ims:reversal-ready',install);install();
window.IMSReversalStatus=Object.freeze({install,reverseIncident,reverseDisposition});
window.dispatchEvent(new CustomEvent('ims:reversal-status-ready'));
export{install,reverseIncident,reverseDisposition};