import {db} from '../../firebase-config.js';
import {collection,endAt,getDocs,limit,orderBy,query,startAt} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=v=>String(v||'').replace('T',' ').slice(0,16)||'—';
const variants=s=>[String(s||''),String(s||'').toUpperCase(),String(s||'').toLowerCase(),String(s||'').replace(/\b\w/g,c=>c.toUpperCase())].filter((v,i,a)=>v&&a.indexOf(v)===i);
let timerMove,timerService,busy=false;

async function prefixDocs(collectionName,fields,term){const out=new Map(),c=collection(db,collectionName),jobs=[];for(const field of fields)for(const v of variants(term))jobs.push(getDocs(query(c,orderBy(field),startAt(v),endAt(v+'\uf8ff'),limit(60))));for(const snap of await Promise.all(jobs))for(const d of snap.docs)out.set(d.id,{id:d.id,...d.data()});return[...out.values()];}
function movementRows(rows){return rows.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,100).map(m=>`<tr class="border-t border-slate-800"><td class="p-2">${esc(dateLabel(m.createdAt))}</td><td class="p-2 font-mono">${esc(m.referenceNumber||'—')}</td><td class="p-2"><b class="text-cyan-300">${esc(m.itemAlias||m.itemCode||'—')}</b><div class="text-[10px] text-slate-500">${esc(m.itemNameSnapshot||'')}</div></td><td class="p-2">${esc(m.fromName||'')} → ${esc(m.toName||'')}</td><td class="p-2">${esc(m.qty)} ${esc(m.unit||'')}</td><td class="p-2">${esc(m.status||'')}</td><td class="p-2">${String(m.status||'').toLowerCase()==='reversed'?`<span class="text-slate-500">Reversed<br>${esc(m.reversalRemark||'')}</span>`:`<button class="revHistoryMove bg-red-700 hover:bg-red-600 px-3 py-2 rounded-lg text-xs font-bold" data-id="${esc(m.id)}">Reverse</button>`}</td></tr>`).join('')||'<tr><td colspan="7" class="p-4 text-slate-500">No matching movements in Firestore history.</td></tr>';}
function serviceRows(rows){return rows.sort((a,b)=>String(b.createdAt||b.serviceDate||'').localeCompare(String(a.createdAt||a.serviceDate||''))).slice(0,100).map(c=>`<tr class="border-t border-slate-800"><td class="p-2">${esc(dateLabel(c.createdAt||c.serviceDate))}</td><td class="p-2 font-mono">${esc(c.serviceReference||c.serviceNo||'—')}</td><td class="p-2"><b class="text-cyan-300">${esc(c.itemAlias||c.itemCode||'—')}</b><div class="text-[10px] text-slate-500">${esc(c.itemName||'')}</div></td><td class="p-2">${esc(c.sourceName||'')} → ${esc(c.providerName||'')}</td><td class="p-2">${esc(c.qty)} ${esc(c.unit||'')}</td><td class="p-2">${esc(c.status||'')}</td><td class="p-2">${String(c.status||'').toLowerCase()==='reversed'?`<span class="text-slate-500">Reversed<br>${esc(c.reversalRemark||'')}</span>`:`<button class="revHistoryService bg-red-700 hover:bg-red-600 px-3 py-2 rounded-lg text-xs font-bold" data-id="${esc(c.id)}">Reverse</button>`}</td></tr>`).join('')||'<tr><td colspan="7" class="p-4 text-slate-500">No matching service cycles in Firestore history.</td></tr>';}
async function reverse(kind,id){if(busy)return;const remark=prompt('Reversal remark (required)');if(!remark?.trim())return;if(!confirm(`Reverse this ${kind==='movement'?'Movement':'Service Cycle'}?\n\nThe original transaction will remain in history.`))return;busy=true;try{if(kind==='movement')await window.IMSReversal?.reverseMovement?.(id,remark.trim());else await window.IMSReversal?.reverseService?.(id,remark.trim());alert('Reversal completed.');await window.IMSReversal?.show?.();}catch(e){alert('Reversal failed: '+(e?.message||e));}finally{busy=false;}}
function bindButtons(){document.querySelectorAll('.revHistoryMove').forEach(b=>b.onclick=()=>reverse('movement',b.dataset.id));document.querySelectorAll('.revHistoryService').forEach(b=>b.onclick=()=>reverse('service',b.dataset.id));}
async function searchMovement(){const input=$('revMoveSearch'),body=$('revMoveBody');if(!input||!body)return;const term=input.value.trim();if(!term)return;body.innerHTML='<tr><td colspan="7" class="p-4 text-slate-500">Searching full Movement history…</td></tr>';try{const rows=await prefixDocs('movements',['referenceNumber','itemAlias','itemCode'],term);body.innerHTML=movementRows(rows);bindButtons();}catch(e){body.innerHTML=`<tr><td colspan="7" class="p-4 text-amber-300">History search failed: ${esc(e?.message||e)}</td></tr>`;}}
async function searchService(){const input=$('revServiceSearch'),body=$('revServiceBody');if(!input||!body)return;const term=input.value.trim();if(!term)return;body.innerHTML='<tr><td colspan="7" class="p-4 text-slate-500">Searching full Service history…</td></tr>';try{const rows=await prefixDocs('service_cycles',['serviceReference','serviceNo','itemAlias','itemCode'],term);body.innerHTML=serviceRows(rows);bindButtons();}catch(e){body.innerHTML=`<tr><td colspan="7" class="p-4 text-amber-300">History search failed: ${esc(e?.message||e)}</td></tr>`;}}
function install(){const m=$('revMoveSearch'),s=$('revServiceSearch');if(m&&!m.dataset.fullHistory){m.dataset.fullHistory='1';m.placeholder='PO / SN / Item ID prefix — searches full history';const note=document.createElement('div');note.className='text-[10px] text-emerald-400';note.textContent='Search is Firestore-backed across full history; blank search shows the latest 100.';m.insertAdjacentElement('afterend',note);m.addEventListener('input',()=>{clearTimeout(timerMove);if(m.value.trim())timerMove=setTimeout(searchMovement,350);});m.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timerMove);searchMovement();}});}if(s&&!s.dataset.fullHistory){s.dataset.fullHistory='1';s.placeholder='Service No. / SN / Item ID prefix — searches full history';const note=document.createElement('div');note.className='text-[10px] text-emerald-400';note.textContent='Search is Firestore-backed across full history; blank search shows the latest 100.';s.insertAdjacentElement('afterend',note);s.addEventListener('input',()=>{clearTimeout(timerService);if(s.value.trim())timerService=setTimeout(searchService,350);});s.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timerService);searchService();}});}}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,40);}).observe(document.body,{childList:true,subtree:true});window.addEventListener('ims:reversal-ready',install);install();
window.IMSReversalSearch=Object.freeze({install,searchMovement,searchService});
window.dispatchEvent(new CustomEvent('ims:reversal-search-ready'));
export{install,searchMovement,searchService};
