import { db } from '../../firebase-config.js';
import { collection, documentId, getCountFromServer, getDocs, limit, orderBy, query, startAfter, where } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import { can } from '../../ims-permissions.js';

const byId=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),PAGE_SIZE=20,TAB_KEY='ims.workspace.tab';
const savedTab=()=>{try{const x=sessionStorage.getItem(TAB_KEY);return['register','movement','service'].includes(x)?x:'register';}catch{return'register';}};
const rememberTab=x=>{try{sessionStorage.setItem(TAB_KEY,x);}catch{}};
let initialShown=false,showing=false,activeTab=savedTab(),recent=[];
const queues={
 transit:{rows:[],page:0,total:0,cursors:[null],last:null,loading:false},
 supplier:{rows:[],page:0,total:0,cursors:[null],last:null,loading:false},
 client:{rows:[],page:0,total:0,cursors:[null],last:null,loading:false},
 service:{rows:[],page:0,total:0,cursors:[null],last:null,loading:false}
};
function identity(i){const alias=i.alias||i.itemAlias||'No Alias',name=i.name||i.itemName||i.itemNameSnapshot||'',id=i.itemCode||'';return`<div class="min-w-0"><div class="font-semibold text-sm"><span class="text-cyan-300">${esc(alias)}</span>${name?` · <span class="text-slate-100">${esc(name)}</span>`:''}</div>${id?`<div class="font-mono text-[9px] text-slate-600 mt-0.5">IMS Item ID: ${esc(id)}</div>`:''}</div>`;}
function meta(label,value){if(value===undefined||value===null||value==='')return'';return`<div class="min-w-0"><span class="text-[9px] uppercase tracking-wide text-slate-600">${esc(label)}</span><div class="text-[11px] text-slate-300 break-words">${esc(value)}</div></div>`;}
function setHead(){if(byId('pageTitle'))byId('pageTitle').textContent='Main Workspace';if(byId('pageSubtitle'))byId('pageSubtitle').textContent='Registration, movement and service cycles in focused operational views.';document.querySelectorAll('.navBtn').forEach(b=>b.className=`navBtn text-left px-3 py-2.5 rounded-xl text-xs font-semibold ${b.dataset.tab==='workspace'?'bg-red-600 text-white':'bg-slate-800/50 hover:bg-slate-800'}`);}
function card(title,id,body=''){return `<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><div class="flex items-center justify-between gap-3 mb-4"><h2 class="font-bold text-sm sm:text-base">${esc(title)}</h2></div><div id="${id}">${body}</div></section>`;}
async function loadRecent(){const snap=await getDocs(query(collection(db,'inventory'),orderBy('createdAt','desc'),limit(20)));recent=snap.docs.map(d=>({id:d.id,...d.data()}));}
function queueBase(kind){if(kind==='transit')return query(collection(db,'movements'),where('status','==','in_transit'),orderBy(documentId(),'asc'));if(kind==='supplier')return query(collection(db,'inventory'),where('status','==','At Supplier'),orderBy(documentId(),'asc'));if(kind==='client')return query(collection(db,'inventory'),where('status','==','At Client'),orderBy(documentId(),'asc'));return query(collection(db,'service_cycles'),where('status','in',['active','ready_return','return_transit','failed']),orderBy(documentId(),'asc'));}
async function loadQueue(kind,reset=false){const s=queues[kind];if(s.loading)return;s.loading=true;try{if(reset){s.page=0;s.cursors=[null];s.last=null;}const base=queueBase(kind),cursor=s.cursors[s.page],pageQ=cursor?query(base,startAfter(cursor),limit(PAGE_SIZE)):query(base,limit(PAGE_SIZE));const[snap,countSnap]=await Promise.all([getDocs(pageQ),getCountFromServer(base)]);s.rows=snap.docs.map(d=>({id:d.id,...d.data()}));s.total=countSnap.data().count||0;s.last=snap.docs.at(-1)||null;if(s.last)s.cursors[s.page+1]=s.last;}finally{s.loading=false;}}
async function load(){if(activeTab==='register')return loadRecent();if(activeTab==='movement')return Promise.all([loadQueue('transit',true),loadQueue('supplier',true),loadQueue('client',true)]);if(activeTab==='service')return loadQueue('service',true);}
function recentRegisteredHtml(){return`<div class="space-y-2">${recent.map(i=>`<button class="workspaceOpenItem w-full text-left bg-slate-950 border border-slate-800 rounded-lg p-3" data-id="${i.id}">${identity(i)}<div class="grid sm:grid-cols-3 gap-2 mt-2">${meta('Category',i.category)}${meta('Location',i.currentLocation)}${meta('PO',i.ourPONumber)}</div></button>`).join('')||'<div class="text-xs text-slate-500">No registered items.</div>'}</div>`;}
function transitRow(r){return`<div class="bg-slate-950 border border-slate-800 rounded-xl p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><button class="workspaceOpenItem text-left min-w-0 flex-1" data-id="${esc(r.itemId||'')}">${identity({alias:r.itemAlias,itemCode:r.itemCode,name:r.itemNameSnapshot})}<div class="grid sm:grid-cols-2 lg:grid-cols-5 gap-2 mt-2">${meta('Reference',`${r.referenceLabel||'Reference'} ${r.referenceNumber||''}`.trim())}${meta('From',r.fromName)}${meta('To',r.toName)}${meta('Qty',`${Number(r.qty||0)} ${r.unit||''}`.trim())}${meta('Status','In Transit')}</div>${r.logisticsProviderName||r.transportNo||r.logisticsReference?`<div class="grid sm:grid-cols-3 gap-2 mt-2 pt-2 border-t border-slate-900">${meta('Logistics',r.logisticsProviderName)}${meta('Transport / Vessel',r.transportNo)}${meta('Delivery Ref',r.logisticsReference)}</div>`:''}</button>${can('movement.edit')?`<button class="imsArrive shrink-0 bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-lg text-xs font-bold" data-id="${r.id}">Arrive</button>`:''}</div>`;}
function locationRow(r,kind){const party=kind==='supplier'?(r.supplierName||r.ownerBusinessName||r.currentLocation||'Supplier'):(r.clientName||r.currentLocation||'Client'),wanted=kind==='supplier'?'At Supplier':'At Client',qty=Array.isArray(r.stockBalances)?r.stockBalances.filter(b=>b.status===wanted).reduce((n,b)=>n+Number(b.qty||0),0):Number(r.quantity||0);return`<button class="workspaceOpenItem w-full text-left bg-slate-950 border border-slate-800 rounded-xl p-3 hover:border-cyan-800" data-id="${esc(r.id)}">${identity(r)}<div class="grid sm:grid-cols-2 lg:grid-cols-6 gap-2 mt-2">${meta(kind==='supplier'?'Supplier':'Client',party)}${meta('Category',r.category)}${meta('Ownership',r.ownershipType==='third_party'?'R2R / Third-Party':'Owned')}${meta('PO',r.ourPONumber)}${meta('Qty',`${qty} ${r.unit||''}`.trim())}${meta('Status',r.status)}</div></button>`;}
function serviceRow(r){const st=r.status==='return_transit'?'Return In Transit':r.status==='ready_return'?'Ready to Return':r.status==='failed'?'Failed':'Under Service';return`<button class="workspaceOpenItem w-full text-left bg-slate-950 border border-slate-800 rounded-lg p-3" data-id="${esc(r.itemId||'')}">${identity({alias:r.itemAlias,itemCode:r.itemCode,name:r.itemName})}<div class="grid sm:grid-cols-2 lg:grid-cols-6 gap-2 mt-2">${meta('Service No.',r.serviceNo)}${meta('Type',r.serviceType||'Service')}${meta('Provider',r.providerName)}${meta('Mode',r.serviceMode)}${meta('Source',r.sourceName)}${meta('Status',st)}</div>${r.returnName?`<div class="mt-2">${meta('Return Destination',r.returnName)}</div>`:''}</button>`;}
function queueRows(kind){const s=queues[kind];if(kind==='transit')return s.rows.map(transitRow).join('');if(kind==='supplier'||kind==='client')return s.rows.map(r=>locationRow(r,kind)).join('');return s.rows.map(serviceRow).join('');}
function queueSection(kind,title,subtitle=''){const s=queues[kind],from=s.total?s.page*PAGE_SIZE+1:0,to=Math.min((s.page+1)*PAGE_SIZE,s.total),pages=Math.max(1,Math.ceil(s.total/PAGE_SIZE)),rows=queueRows(kind)||'<div class="text-sm text-slate-500">No records.</div>';return`<section class="w-full bg-slate-900 border border-slate-800 rounded-2xl p-4" data-workspace-queue="${kind}"><div class="flex flex-wrap justify-between gap-2 items-start mb-3"><div><div class="font-bold">${esc(title)}</div>${subtitle?`<div class="text-[10px] text-slate-500 mt-0.5">${esc(subtitle)}</div>`:''}<div class="text-[10px] text-emerald-400 mt-1">${from}-${to} of ${s.total} · Firestore server pagination · 20 per page</div></div><div class="text-xs text-slate-500">${s.page+1}/${pages}</div></div><div class="space-y-2">${rows}</div><div class="flex justify-between mt-3"><button class="workspaceQueuePage bg-slate-800 px-3 py-2 rounded text-xs disabled:opacity-40" data-kind="${kind}" data-dir="-1" ${s.page<=0?'disabled':''}>Previous</button><button class="workspaceQueuePage bg-slate-800 px-3 py-2 rounded text-xs disabled:opacity-40" data-kind="${kind}" data-dir="1" ${to>=s.total?'disabled':''}>Next</button></div></section>`;}
function workspaceTabs(){return`<div class="flex flex-wrap gap-2 mb-5">${[['register','Register Item'],['movement','Movement'],['service','Service Cycle']].map(([id,label])=>`<button class="workspaceTab px-4 py-2 rounded-lg text-xs font-bold ${activeTab===id?'bg-red-600 text-white':'bg-slate-800'}" data-workspace-tab="${id}">${label}</button>`).join('')}</div>`;}
function operationHtml(){if(activeTab==='register')return`<div class="space-y-5">${card('Register Item','registerForm','Loading Registration…')}${card('Recently Added','workspaceRecent',recentRegisteredHtml())}</div>`;if(activeTab==='movement')return`<div class="space-y-5">${card('Movement — Supplier / Warehouse / Client','moveForm','Loading Movement…')}${queueSection('transit','In Transit / Arrival','Physical movements waiting for arrival')}${queueSection('supplier','At Supplier','Items currently physically recorded at suppliers')}${queueSection('client','At Client','Items currently physically recorded at clients')}</div>`;return`<div class="space-y-5">${card('Service Cycle','serviceCycleForm','Loading Service Cycle…')}${queueSection('service','Currently Under Service','Active, failed, ready-return and return-transit service items')}</div>`;}
function bindOpenItems(root=document){root.querySelectorAll('.workspaceOpenItem').forEach(b=>b.onclick=()=>b.dataset.id&&(window.IMSAlphaUsability?.openItemDetail?window.IMSAlphaUsability.openItemDetail(b.dataset.id):window.IMSItems?.showItem?window.IMSItems.showItem(b.dataset.id):window.openItem?.(b.dataset.id)));}
function bindArrive(root=document){root.querySelectorAll('.imsArrive').forEach(b=>b.onclick=()=>{rememberTab('movement');return window.IMSMovement?.arriveMovement?window.IMSMovement.arriveMovement(b.dataset.id):window.arriveMovement?.(b.dataset.id);});}
function bindQueueControls(root=document){root.querySelectorAll('.workspaceQueuePage').forEach(b=>b.onclick=()=>changeQueuePage(b.dataset.kind,Number(b.dataset.dir||0)));}
async function changeQueuePage(kind,dir){const s=queues[kind];if(dir>0){if((s.page+1)*PAGE_SIZE>=s.total||!s.last)return;s.page++;}else{if(s.page<=0)return;s.page--;}await loadQueue(kind,false);const old=document.querySelector(`[data-workspace-queue="${kind}"]`);if(!old)return;const wrap=document.createElement('div');const titles={transit:['In Transit / Arrival','Physical movements waiting for arrival'],supplier:['At Supplier','Items currently physically recorded at suppliers'],client:['At Client','Items currently physically recorded at clients'],service:['Currently Under Service','Active, failed, ready-return and return-transit service items']},[title,subtitle]=titles[kind];wrap.innerHTML=queueSection(kind,title,subtitle);const next=wrap.firstElementChild;old.replaceWith(next);bindOpenItems(next);bindArrive(next);bindQueueControls(next);}
function bind(){document.querySelectorAll('.workspaceTab').forEach(b=>b.onclick=async()=>{activeTab=b.dataset.workspaceTab;rememberTab(activeTab);await load();await render();});bindOpenItems();bindArrive();bindQueueControls();}
async function mountActiveOperation(){try{if(activeTab==='register'){if(window.IMSRegistration?.mount)return window.IMSRegistration.mount();window.addEventListener('ims:registration-ready',()=>window.IMSRegistration?.mount?.(),{once:true});return;}if(activeTab==='movement'){if(window.IMSMovement?.mount)return window.IMSMovement.mount();window.addEventListener('ims:movement-ready',()=>window.IMSMovement?.mount?.(),{once:true});return;}if(activeTab==='service'){if(window.IMSServiceCycle?.mount)return window.IMSServiceCycle.mount();window.addEventListener('ims:service-cycle-ready',()=>window.IMSServiceCycle?.mount?.(),{once:true});}}catch(err){console.error(`IMS ${activeTab} mount failed:`,err);const id=activeTab==='register'?'registerForm':activeTab==='movement'?'moveForm':'serviceCycleForm',m=byId(id);if(m)m.innerHTML=`<div class="border border-red-900 rounded-xl p-3 text-xs text-red-300">Unable to load ${esc(activeTab)}: ${esc(err?.message||err)}</div>`;}}
async function render(mountOperation=true){setHead();byId('appContent').innerHTML=`<div data-ims-workspace-module="4">${workspaceTabs()}<div id="workspaceOperation">${operationHtml()}</div><div id="itemDetailMount" class="mt-5"></div></div>`;bind();if(mountOperation)await mountActiveOperation();window.dispatchEvent(new CustomEvent('ims:workspace-rendered',{detail:{tab:activeTab}}));}
async function show(tab=activeTab){if(!can('app.view')||showing)return;activeTab=['register','movement','service'].includes(tab)?tab:savedTab();rememberTab(activeTab);showing=true;try{await load();await render();}catch(err){console.error('IMS workspace failed:',err);alert('Unable to load Main Workspace: '+(err?.message||err));}finally{showing=false;}}
function takeOwnership(){const b=document.querySelector('[data-tab="workspace"]');if(!b)return;b.dataset.imsWorkspaceOwned='1';b.onclick=()=>show(savedTab());const open=/Main Workspace/i.test(byId('pageTitle')?.textContent||'')&&!document.querySelector('[data-ims-workspace-module]');if(open&&!initialShown){initialShown=true;show(savedTab());}}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(takeOwnership,30);}).observe(document.body,{childList:true,subtree:true});takeOwnership();window.IMSWorkspace=Object.freeze({show,load,render,mountActiveOperation,loadQueue});window.dispatchEvent(new CustomEvent('ims:workspace-ready'));export {show,load,render,mountActiveOperation,loadQueue};