import {db} from '../../firebase-config.js';
import {collection,getCountFromServer,getDocs,limit,orderBy,query,startAfter,where} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const PAGE_SIZE=50;
const DIRECTORY_STATUS=['At Supplier','Available','Reserved','At Client','Maintenance','Inspection','Not Available','In Transit'];
const INACTIVE_STATUS=['Missing','Stolen','Disposed - Sold','Disposed - Scrapped','Written Off','Returned to Supplier','Returned to Owner','Disposed - Other'];
const SORT_FIELDS=[
  ['Wellora SN / R2R SN','alias'],
  ['Description','name'],
  ['Supplier / Owner','supplierName'],
  ['Location / Distribution','currentLocation']
];
let sortField='',sortDir='asc',page=0,cursors=[null],loading=false,armed=false,lastScope='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function balances(i){return(Array.isArray(i?.stockBalances)?i.stockBalances:[]).filter(b=>Number(b.qty||0)>0).map(b=>({...b,qty:Number(b.qty||0),locationName:b.locationName||b.location||'Unknown',status:b.status||'Not Available'}));}
function qty(i){return balances(i).reduce((a,b)=>a+b.qty,0)}function live(i){return balances(i).filter(b=>!['Disposed - Sold','Disposed - Scrapped','Written Off','Returned to Supplier','Returned to Owner','Disposed - Other'].includes(b.status)).reduce((a,b)=>a+b.qty,0)}function avail(i){return balances(i).filter(b=>b.status==='Available').reduce((a,b)=>a+b.qty,0)}function dist(i){return balances(i).map(b=>`${b.locationName}: ${b.qty} (${b.status})`).join(' · ')}
function scope(){return document.getElementById('stockInactive')?.className.includes('bg-red-600')?'inactive':'directory';}
function activeConstraint(){const alias=document.getElementById('stockAliasFilter')?.value.trim()||'',name=document.getElementById('stockNameFilter')?.value.trim()||'',filters=[['category',document.getElementById('stockCategoryFilter')?.value||''],['status',document.getElementById('stockStatusFilter')?.value||''],['currentLocation',document.getElementById('stockLocationFilter')?.value||''],['ownershipType',document.getElementById('stockOwnershipFilter')?.value||'']].filter(x=>x[1]);const exact=alias?['alias',alias]:name?['name',name]:null,all=[...(exact?[exact]:[]),...filters];return all;}
function buildBase(){const c=collection(db,'inventory'),parts=[],constraints=activeConstraint(),s=scope(),statusConstraint=constraints.find(x=>x[0]==='status');if(statusConstraint)parts.push(where('status','==',statusConstraint[1]));else parts.push(where('status','in',s==='inactive'?INACTIVE_STATUS:DIRECTORY_STATUS));for(const [field,value] of constraints)if(field!=='status')parts.push(where(field,'==',value));if(sortField)parts.push(orderBy(sortField,sortDir));return query(c,...parts);}
function rowHtml(i){const b=balances(i),status=[...new Set(b.map(x=>x.status))].join(' / ')||i.status||'',ownership=i.ownershipType==='third_party'?'Third-Party / R2R':'Owned',supplier=i.supplierName||i.ownerBusinessName||'',total=qty(i);return`<tr class="border-t border-slate-800"><td class="px-3 py-2"><button class="stockServerOpen text-cyan-300 font-bold underline" data-id="${i.id}">${esc(i.alias||'—')}</button></td><td class="px-3 py-2 font-semibold">${esc(i.name||'')}</td><td class="px-3 py-2">${esc(i.type||'')}</td><td class="px-3 py-2">${esc(i.category||'')}</td><td class="px-3 py-2">${esc(i.size||'')}</td><td class="px-3 py-2">${esc(i.grade||'')}</td><td class="px-3 py-2">${esc(i.ppf||'')}</td><td class="px-3 py-2">${esc(i.connection||'')}</td><td class="px-3 py-2">${esc(i.range||'')}</td><td class="px-3 py-2">${esc(i.brand||'')}</td><td class="px-3 py-2">${esc(i.model||'')}</td><td class="px-3 py-2">${esc(ownership)}</td><td class="px-3 py-2">${esc(supplier)}</td><td class="px-3 py-2">${esc(i.ourPONumber||'')}</td><td class="px-3 py-2">${total}</td><td class="px-3 py-2 font-bold">${live(i)}</td><td class="px-3 py-2">${avail(i)}</td><td class="px-3 py-2">${esc(status)}</td><td class="px-3 py-2">${esc(dist(i))}</td><td class="px-3 py-2 font-mono text-[10px] text-slate-500 whitespace-nowrap">${esc(i.itemCode||'')}</td></tr>`;}
async function load(reset=false){if(!sortField||loading||!document.querySelector('#stockTable table'))return;if(reset){page=0;cursors=[null];}const constraints=activeConstraint();if(constraints.length>1){alert('Use only one exact search or one filter together with server sorting.');return;}loading=true;try{const base=buildBase(),cursor=cursors[page],pageQ=cursor?query(base,startAfter(cursor),limit(PAGE_SIZE)):query(base,limit(PAGE_SIZE));const[snap,countSnap]=await Promise.all([getDocs(pageQ),getCountFromServer(base)]),docs=snap.docs.map(d=>({id:d.id,...d.data()})),total=countSnap.data().count||0;if(snap.docs.length)cursors[page+1]=snap.docs.at(-1);const table=document.querySelector('#stockTable table'),tbody=table?.tBodies?.[0];if(!tbody)return;tbody.innerHTML=docs.map(rowHtml).join('')||'<tr><td colspan="20" class="p-6 text-slate-500">No matching inventory records.</td></tr>';document.querySelectorAll('.stockServerOpen').forEach(b=>b.onclick=()=>window.IMSItems?.showItem?.(b.dataset.id));const start=total?page*PAGE_SIZE+1:0,end=Math.min(page*PAGE_SIZE+docs.length,total),footer=document.querySelector('#stockTable .flex.justify-between.items-center.mt-3');if(footer){footer.innerHTML=`<span>Showing ${start}–${end} of ${total} · Page ${page+1}/${Math.max(1,Math.ceil(total/PAGE_SIZE))} · Server sort ${sortField} ${sortDir==='asc'?'↑':'↓'}</span><span><button id="stockServerPrev" class="bg-slate-800 px-3 py-2 rounded disabled:opacity-40" ${page===0?'disabled':''}>Previous</button> <button id="stockServerNext" class="bg-slate-800 px-3 py-2 rounded disabled:opacity-40" ${end>=total?'disabled':''}>Next</button></span>`;document.getElementById('stockServerPrev')?.addEventListener('click',()=>{if(page>0){page--;load(false)}});document.getElementById('stockServerNext')?.addEventListener('click',()=>{if(end<total){page++;load(false)}});}const note=document.querySelector('#stockTable > div:first-child');if(note)note.textContent=`${scope()==='inactive'?'Inactive':'Item Directory'} · Firestore server sort: ${sortField} ${sortDir==='asc'?'ascending':'descending'} · ${start}–${end} of ${total}.`;markHeaders();}catch(e){console.error('IMS Firestore server sort failed:',e);alert(`This Firestore sort/filter combination is unavailable without an index. No index was changed.\n\n${e?.message||e}`);}finally{loading=false;}}
function headerField(th){const text=(th.textContent||'').replace(/[↕↑↓]/g,'').replace(/\s+/g,' ').trim();const hit=SORT_FIELDS.find(([label])=>text===label||text.startsWith(label));return hit?.[1]||'';}
function markHeaders(){const table=document.querySelector('#stockTable table');if(!table)return;for(const th of table.querySelectorAll('thead th')){const field=headerField(th),old=th.querySelector('.imsServerSortMark');if(old)old.remove();th.style.cursor='';th.title='';delete th.dataset.serverSortField;if(!field)continue;th.style.cursor='pointer';th.title='Firestore server sort';th.dataset.serverSortField=field;const mark=document.createElement('span');mark.className='imsServerSortMark text-cyan-400 ml-1';mark.textContent=field===sortField?(sortDir==='asc'?'↑':'↓'):'↕';th.appendChild(mark);if(!th.dataset.serverSortBound){th.dataset.serverSortBound='1';th.addEventListener('click',()=>{const f=th.dataset.serverSortField;if(!f)return;if(sortField===f)sortDir=sortDir==='asc'?'desc':'asc';else{sortField=f;sortDir='asc';}armed=true;load(true);});}}}
function bindApply(){const apply=document.getElementById('stockApplyFilter');if(apply&&!apply.dataset.serverSortWrapped){apply.dataset.serverSortWrapped='1';apply.addEventListener('click',()=>setTimeout(()=>{if(armed)load(true)},120));}const clear=document.getElementById('stockClearFilters');if(clear&&!clear.dataset.serverSortWrapped){clear.dataset.serverSortWrapped='1';clear.addEventListener('click',()=>setTimeout(()=>{if(armed)load(true)},120));}}
function scan(){const table=document.querySelector('#stockTable table');if(!table)return;const s=scope();if(s!==lastScope){lastScope=s;page=0;cursors=[null];}markHeaders();bindApply();if(armed&&!loading){const body=table.tBodies?.[0];if(body&&!body.dataset.serverSorted){body.dataset.serverSorted='1';setTimeout(()=>load(true),20);}}}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(scan,50)}).observe(document.body,{childList:true,subtree:true});scan();
window.IMSInventoryServerSort=Object.freeze({load});
window.dispatchEvent(new CustomEvent('ims:inventory-server-sort-ready'));
export{load};