import {auth,db} from '../../firebase-config.js';
import {addDoc,collection,doc,documentId,getDoc,getDocs,limit,orderBy,query,startAfter,Timestamp,writeBatch} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import {can} from '../../ims-permissions.js';
import {rebuildInventorySummary} from '../inventory/inventory-summary.js';

const BACKUP_VERSION=8;
const READ_BATCH=500,WRITE_BATCH=400,PORTABLE_WARNING_AT=50000;
const BACKUP_COLLECTIONS=Object.freeze([
  'registration_batches','inventory',
  'movement_groups','movements','reservation_events','service_cycles','reversals',
  'client_docs','supplier_docs','document_refs',
  'operational_logs','audit_traces',
  'supplier_profiles','client_profiles','settings','users'
]);
const RETIRED_SETTING_TYPES=new Set(['model','specification']);
const $=id=>document.getElementById(id),now=()=>new Date().toISOString();

async function activeSuperadmin(){const user=auth.currentUser;if(!user)throw new Error('Sign in required.');const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists())throw new Error('User profile missing.');const p=snap.data();if(p.status!=='active'||p.role!=='superadmin')throw new Error('Active superadmin profile required.');return{uid:user.uid,email:p.email||user.email||'',role:p.role};}
function encode(v){if(v===null||v===undefined||typeof v!=='object')return v;if(typeof v.toDate==='function'&&typeof v.seconds==='number')return{__imsType:'timestamp',seconds:v.seconds,nanoseconds:v.nanoseconds||0};if(Array.isArray(v))return v.map(encode);const out={};for(const k of Object.keys(v))out[k]=encode(v[k]);return out;}
function decode(v){if(v===null||v===undefined||typeof v!=='object')return v;if(v.__imsType==='timestamp'&&Number.isFinite(Number(v.seconds)))return new Timestamp(Number(v.seconds),Number(v.nanoseconds||0));if(Array.isArray(v))return v.map(decode);const out={};for(const k of Object.keys(v))out[k]=decode(v[k]);return out;}
function retiredSetting(row){return row?.data&&RETIRED_SETTING_TYPES.has(String(row.data.type||'').trim().toLowerCase());}
async function readCollection(name){const rows=[];let cursor=null;while(true){const parts=[orderBy(documentId()),limit(READ_BATCH)];if(cursor)parts.splice(1,0,startAfter(cursor));const snap=await getDocs(query(collection(db,name),...parts));for(const d of snap.docs){const row={id:d.id,data:encode(d.data())};if(name==='settings'&&retiredSetting(row))continue;rows.push(row);}if(snap.size<READ_BATCH)break;cursor=snap.docs.at(-1);}return rows;}
function download(name,payload){const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
async function audit(action,after,remark,actor,fileName=''){await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType:action,module:'Backup / Recovery',targetType:'backup',targetName:action==='CREATE_SYSTEM_BACKUP'?'Portable IMS Backup':'Portable IMS Restore',targetId:'',summary:String(action).replace(/_/g,' '),beforeValue:null,afterValue:after,changedFields:Object.keys(after||{}),remark,metadata:fileName?{fileName}:{},performedBy:actor.email,performedByRole:actor.role,performedAt:now()});}

async function createBackup(){if(!can('backup.create'))return;const btn=$('imsFullBackup');if(btn){btn.disabled=true;btn.textContent='Preparing Full Backup...';}try{const actor=await activeSuperadmin(),payload={imsBackupVersion:BACKUP_VERSION,createdAt:now(),createdBy:actor.email,backupClass:'portable-browser',productionDisasterRecovery:false,restoreMode:'replace matching document IDs; preserve documents absent from backup; preserve existing immutable reversal records; rebuild derived inventory summary after restore',firebaseAuthIncluded:false,derivedCollectionsExcluded:['inventory_summary'],retiredSettingsExcluded:[...RETIRED_SETTING_TYPES],collections:{}};let total=0;for(const name of BACKUP_COLLECTIONS){payload.collections[name]=await readCollection(name);total+=payload.collections[name].length;}payload.counts=Object.fromEntries(BACKUP_COLLECTIONS.map(name=>[name,payload.collections[name].length]));if(total>=PORTABLE_WARNING_AT&&!confirm(`This full backup contains ${total.toLocaleString()} records. Continue?`))return;await audit('CREATE_SYSTEM_BACKUP',{backupVersion:BACKUP_VERSION,collections:BACKUP_COLLECTIONS.length,records:total,reversals:payload.counts.reversals||0,backupClass:'portable-browser',retiredSettingsExcluded:[...RETIRED_SETTING_TYPES]},'Full portable backup created, including reversal history. Retired Model / Specification settings excluded.',actor);download(`IMS_Full_Backup_v${BACKUP_VERSION}_${payload.createdAt.slice(0,10)}.json`,payload);alert(`Full IMS backup created.\n\nVersion: ${BACKUP_VERSION}\nRecords: ${total}\nCollections: ${BACKUP_COLLECTIONS.length}\nReversals: ${payload.counts.reversals||0}`);}catch(e){console.error('IMS full backup failed:',e);alert('Backup failed: '+(e?.message||e));}finally{if(btn){btn.disabled=false;btn.textContent='Download Full Backup JSON';}}}
function validate(payload){if(!payload||Number(payload.imsBackupVersion)!==BACKUP_VERSION||!payload.collections||typeof payload.collections!=='object')throw new Error(`Unsupported IMS backup. Full backup version ${BACKUP_VERSION} is required.`);for(const name of BACKUP_COLLECTIONS)if(!Array.isArray(payload.collections[name]))throw new Error(`Backup is incomplete: missing collection ${name}.`);return BACKUP_COLLECTIONS;}
function summary(payload,names){return{text:names.map(n=>`${n}: ${payload.collections[n].length}`).join('\n'),total:names.reduce((a,n)=>a+payload.collections[n].length,0)};}
async function restoreBackup(file){if(!can('backup.restore')||!file)return;let payload,names;try{payload=JSON.parse(await file.text());names=validate(payload);}catch(e){alert(e?.message||'Invalid backup file.');return;}const s=summary(payload,names);if(!confirm(`FULL IMS RESTORE v${BACKUP_VERSION}\n\nBackup date: ${payload.createdAt||'Unknown'}\nRecords: ${s.total}\nReversals: ${payload.collections.reversals.length}\n\n${s.text}\n\nMatching IDs will be restored; existing immutable reversal records will be preserved. Retired Model / Specification settings will be ignored. Inventory Summary will be rebuilt. Continue?`))return;if(prompt('Type RESTORE IMS to confirm.','')!=='RESTORE IMS')return;const btn=$('imsFullRestore');if(btn){btn.disabled=true;btn.textContent='Restoring Full Backup...';}let restored=0,skipped=0,skippedImmutable=0,skippedRetiredSettings=0;const errors=[];try{const actor=await activeSuperadmin();for(const name of names){const rows=payload.collections[name];for(let i=0;i<rows.length;i+=WRITE_BATCH){const part=rows.slice(i,i+WRITE_BATCH),batch=writeBatch(db);let queued=0;for(const row of part){if(!row?.id||row.data===undefined){errors.push(`${name}: invalid record`);continue;}if(name==='settings'&&retiredSetting(row)){skippedRetiredSettings++;continue;}if(name==='users'&&row.id===actor.uid){skipped++;continue;}if(name==='reversals'){const existing=await getDoc(doc(db,name,row.id));if(existing.exists()){skippedImmutable++;continue;}}batch.set(doc(db,name,row.id),decode(row.data));queued++;}if(queued){try{await batch.commit();restored+=queued;}catch(e){errors.push(`${name} batch ${Math.floor(i/WRITE_BATCH)+1}: ${e?.message||e}`);}}}}const rebuilt=await rebuildInventorySummary(actor.email);await audit('RESTORE_SYSTEM_BACKUP',{restored,skippedCurrentUser:skipped,skippedExistingReversals:skippedImmutable,skippedRetiredSettings,errors:errors.length,backupCreatedAt:payload.createdAt||'',backupVersion:payload.imsBackupVersion,reversalsInBackup:payload.collections.reversals.length,inventorySummaryRebuilt:true,inventorySummarySourceRecords:rebuilt.recordCount},'Full portable restore completed. Existing immutable reversal records were preserved and retired Model / Specification settings were ignored.',actor,file.name);if(errors.length)console.error('IMS full restore errors:',errors);alert(`Full IMS restore completed.\n\nRestored: ${restored}\nReversals in backup: ${payload.collections.reversals.length}\nExisting reversals preserved: ${skippedImmutable}\nRetired Model / Specification settings skipped: ${skippedRetiredSettings}\nCurrent signed-in profile preserved: ${skipped}\nErrors: ${errors.length}\nInventory Summary rebuilt from ${rebuilt.recordCount} inventory record(s).`);location.reload();}catch(e){console.error('IMS full restore failed:',e);alert('Restore failed: '+(e?.message||e));}finally{if(btn){btn.disabled=false;btn.textContent='Restore Full Backup JSON';}}}

function install(){if(window.IMS_ROLE!=='superadmin')return;const backup=$('imsFullBackup'),restore=$('imsFullRestore'),file=$('imsFullRestoreFile');if(!backup||!restore||!file)return;backup.textContent='Download Full Backup JSON';restore.textContent='Restore Full Backup JSON';backup.onclick=createBackup;restore.onclick=()=>file.click();file.onchange=e=>restoreBackup(e.target.files?.[0]);const host=$('imsBackupRecoveryModule');if(host&&!host.querySelector('[data-ims-backup-v8="1"]')){const note=document.createElement('div');note.dataset.imsBackupV8='1';note.className='mt-3 text-[11px] text-emerald-300';note.textContent=`Full Backup v${BACKUP_VERSION} includes Reversal history, excludes retired Model / Specification settings, preserves existing immutable reversals on restore, and rebuilds Inventory Summary.`;host.appendChild(note);}}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,50);}).observe(document.body,{childList:true,subtree:true});window.addEventListener('ims:modules-ready',install);install();
window.IMSBackupV8=Object.freeze({createBackup,restoreBackup,install,BACKUP_VERSION,BACKUP_COLLECTIONS});
window.dispatchEvent(new CustomEvent('ims:backup-v8-ready'));
export{createBackup,restoreBackup,install,BACKUP_VERSION,BACKUP_COLLECTIONS};