import {auth,db} from '../../firebase-config.js';
import {addDoc,collection,doc,documentId,getDoc,getDocs,limit,orderBy,query,writeBatch} from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
import {can} from '../../ims-permissions.js';

const WRITE_BATCH=400;
const RESET_COLLECTIONS=Object.freeze([
  'registration_batches','inventory','movement_groups','movements','reservation_events','service_cycles','reversals',
  'client_docs','supplier_docs','document_refs','operational_logs','audit_traces',
  'supplier_profiles','client_profiles','settings'
]);
const DERIVED_RESET_COLLECTIONS=Object.freeze(['inventory_summary']);
const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
async function activeSuperadmin(){const user=auth.currentUser;if(!user)throw new Error('Sign in required.');const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists())throw new Error('User profile missing.');const p=snap.data();if(p.status!=='active'||p.role!=='superadmin')throw new Error('Active superadmin profile required.');return{uid:user.uid,email:p.email||user.email||'',role:p.role};}
async function clearCollection(name){let deleted=0;while(true){const snap=await getDocs(query(collection(db,name),orderBy(documentId()),limit(WRITE_BATCH)));if(snap.empty)break;const batch=writeBatch(db);snap.docs.forEach(d=>batch.delete(d.ref));await batch.commit();deleted+=snap.size;}return deleted;}
async function writeAudit(action,after,remark,actor){await addDoc(collection(db,'audit_traces'),{traceVersion:3,actionType:action,module:'Backup / Recovery',targetType:'system',targetName:action==='CLEAN_TEST_RESET'?'Clean Testing Reset':'System Reload',targetId:'',summary:String(action).replace(/_/g,' '),beforeValue:null,afterValue:after,changedFields:Object.keys(after||{}),remark,performedBy:actor.email,performedByRole:actor.role,performedAt:now()});}
async function cleanTestingReset(){if(!can('system.test.reset'))return;const actor=await activeSuperadmin();if(!confirm('CLEAN TESTING RESET\n\nThis permanently clears IMS test/business data including reversal history while preserving users and Firebase Auth. Continue?'))return;if(prompt('Type CLEAN RESET to confirm.','')!=='CLEAN RESET')return;const btn=$('imsResetDataBtn');if(btn){btn.disabled=true;btn.textContent='Cleaning...';}let deleted=0;try{for(const name of RESET_COLLECTIONS)deleted+=await clearCollection(name);for(const name of DERIVED_RESET_COLLECTIONS)deleted+=await clearCollection(name);await writeAudit('CLEAN_TEST_RESET',{deleted,collections:RESET_COLLECTIONS.length+DERIVED_RESET_COLLECTIONS.length,reversalsCleared:true,inventorySummaryCleared:true},'Clean testing reset completed; users and Firebase Auth preserved.',actor);alert(`Clean testing reset completed.\nDeleted ${deleted} Firestore record(s).`);location.reload();}catch(e){console.error('IMS clean testing reset failed:',e);alert('Reset failed: '+(e?.message||e));}finally{if(btn){btn.disabled=false;btn.textContent='Clean Reset All Test Data';}}}
async function reloadSystem(){if(!can('backup.create'))return;try{const actor=await activeSuperadmin();await writeAudit('SYSTEM_RELOAD',{requestedAt:now()},'Superadmin manually reloaded IMS.',actor);}catch(e){console.warn('IMS reload audit failed:',e);}location.reload();}
function section(){return`<section id="imsBackupRecoveryModule" class="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl"><h2 class="font-bold text-sm sm:text-base mb-2">System Backup / Recovery</h2><p class="text-xs text-slate-400 mb-2">Superadmin only. Full Backup v8 includes reversal history. Portable JSON is for testing, migration and smaller recovery jobs.</p><div class="border border-amber-900/60 bg-amber-950/20 rounded-lg p-3 text-[11px] text-amber-200 mb-3"><b>Production disaster recovery:</b> use Firestore managed/scheduled backups for very large databases. The portable JSON backup is an additional recovery/export tool.</div><div class="flex flex-wrap gap-2"><button id="imsFullBackup" type="button" class="bg-cyan-700 hover:bg-cyan-600 px-4 py-2 rounded-lg text-xs font-bold">Download Full Backup JSON</button><button id="imsFullRestore" type="button" class="bg-amber-700 hover:bg-amber-600 px-4 py-2 rounded-lg text-xs font-bold">Restore Full Backup JSON</button><input id="imsFullRestoreFile" type="file" accept=".json,application/json" class="hidden"><button id="imsReloadSystem" type="button" class="bg-slate-700 hover:bg-slate-600 px-4 py-2 rounded-lg text-xs font-bold">Reload IMS</button></div><div class="mt-4 border-t border-red-900/60 pt-4"><div class="font-bold text-red-300 text-sm">Clean Testing Reset</div><p class="text-xs text-slate-400 mt-1 mb-3">Testing only. Clears IMS business/test data, reversal history and derived summary while preserving users and Firebase Auth.</p><button id="imsResetDataBtn" type="button" class="bg-red-700 hover:bg-red-600 px-4 py-2.5 rounded-lg text-xs font-bold">Clean Reset All Test Data</button></div></section>`;}
function bind(){if($('imsReloadSystem'))$('imsReloadSystem').onclick=reloadSystem;if($('imsResetDataBtn'))$('imsResetDataBtn').onclick=()=>cleanTestingReset().catch(e=>alert('Reset failed: '+(e?.message||e)));window.IMSBackupV8?.install?.();}
function mount(){if(!can('backup.create')&&!can('backup.restore')&&!can('system.test.reset'))return;if($('pageTitle')?.textContent!=='Global Settings')return;const host=$('imsBackupRecoveryHost')||$('appContent');if(!host)return;if(!$('imsBackupRecoveryModule'))host.insertAdjacentHTML('beforeend',section());bind();}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(mount,30);}).observe(document.body,{childList:true,subtree:true});window.addEventListener('ims:backup-v8-ready',bind);mount();
window.IMSBackup=Object.freeze({cleanTestingReset,reloadSystem,mount,RESET_COLLECTIONS,DERIVED_RESET_COLLECTIONS});
window.dispatchEvent(new CustomEvent('ims:backup-ready'));
export{cleanTestingReset,reloadSystem,mount};
